---
title: "CollegeData Dictionary"
output: html_document
---

This dataset contains small colleges (1000-5000 students) that primarily grant bachelor's degrees and require the ACT for admission.  It was originally obtained from [the College Scorecard](https://collegescorecard.ed.gov/data/), a subsidiary of the US Deptartment of Education.

## Variables:

**INSTNM** 	The name of the institution

**CITY**		The city where the institution is located

**STABBR**		Abbreviation of the state where the institution is located

**REGION**		A categorical variable describing the region of the institution:

- 1	New England (CT, ME, MA, NH, RI, VT)
- 2	Mid East (DE, DC, MD, NJ, NY, PA)
- 3	Great Lakes (IL, IN, MI, OH, WI)
- 4	Plains (IA, KS, MN, MO, NE, ND, SD)
- 5	Southeast (AL, AR, FL, GA, KY, LA, MS, NC, SC, TN, VA, WV)
- 6	Southwest (AZ, NM, OK, TX)
- 7	Rocky Mountains (CO, ID, MT, UT, WY)
- 8	Far West (AK, CA, HI, NV, OR, WA)
- 9	Outlying Areas (AS, FM, GU, MH, MP, PR, PW, VI)

**LOCALE** 	A categorical variable describing the location of the institution:

- 11	City: Large (population of 250,000 or more)
- 12	City: Midsize (population of at least 100,000 but less than 250,000)
- 13	City: Small (population less than 100,000)
- 21	Suburb: Large (outside principal city, in urbanized area with population of 250,000 or more)
- 22	Suburb: Midsize (outside principal city, in urbanized area with population of at least 100,000 but less than 250,000)
- 23	Suburb: Small (outside principal city, in urbanized area with population less than 100,000)
- 31	Town: Fringe (in urban cluster up to 10 miles from an urbanized area)
- 32	Town: Distant (in urban cluster more than 10 miles and up to 35 miles from an urbanized area)
- 33	Town: Remote (in urban cluster more than 35 miles from an urbanized area)
- 41	Rural: Fringe (rural territory up to 5 miles from an urbanized area or up to 2.5 miles from an urban cluster)
- 42	Rural: Distant (rural territory more than 5 miles but up to 25 miles from an urbanized area or more than 2.5 and up to 10 miles from an urban cluster)
- 43	Rural: Remote (rural territory more than 25 miles from an urbanized area and more than 10 miles from an urban cluster)

**ADM_RATE**	Percentage of applicants that are admitted in to the institution

**ACTCMMID**	Median cumulative ACT score of enrolled students

**ACTENMID**	Median English ACT subscore of enrolled students

**ACTMTMID**	Median Math ACT subscore of enrolled students

**UGDS**		Total undergraduate enrollment

**PFTFAC**		Percent of faculty that are full time

**PCTPELL**	Percent of students receiving a Pell Grant

**COSTT4_A**	Average yearly cost of attending

**AVGFACSAL**	Average faculty salary
