---
title: "Grinnell Science Project 2025 - Lab Experience in Statistics and Data Science"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
---

$~$

### Planned schedule:

- Tuesday 8/19
    - 1:15-1:45 - Introductions, examples of lab-related descriptions from statistics, data science, and computer science courses and syllabi
    - 1:45-2:30 - Work through Lab 1 from Sta-209 (Applied Statistics)
    - 2:30-2:45 - Break
    - 2:45-2:50 - Debrief Lab 1, discuss next steps
    - 2:50-3:50 - Work through `ggplot` data visualization lab, find/choose data for tomorrow's lab activity
    - 3:50-4:00 - Wrap-up, tips for choice of data
    
- Wednesday 8/20
    - 1:15-1:25 - Questions/thoughts from Tuesday
    - 1:25-2:15 - Icebreaker activity from Sta-330 (Applied Data Science)
    - 2:15-2:30 - Break
    - 2:30-3:15 - Create a multivariable data visualization with your chosen data
    - 3:15-3:30 - Sharing and wrap-up
    
   
### Materials:

- Tuesday 8/19
    - Introduction/Resources:
        - [My own STA-230 (Introduction to Data Science, Fall 23) syllabus](https://remiller1450.github.io/syllabus230f23.html) - Note the statements about class sessions, engagement, and labs
        - [Professor Nolte's STA-209 (Applied Statistics, Spring 25) syllabus](https://collinn.github.io/s25/209/syllabus209s25.html) - Note the sections on labs and engagement/participation
        - [Professor Rebelsky's CSC-151 (Funcational Problem Solving, Spring 25) schedule](https://rebelsky.cs.grinnell.edu/Courses/CSC151/2025Sp/schedule/) - Note 2/17 on "Pair programming"
    - [STA-209 Lab 1](https://remiller1450.github.io/s209s25/R_basics.html)
    - [`ggplot` data visualization lab](https://remiller1450.github.io/s209s24/ggplot1.html)
    - [Finding data for Wednesday](https://remiller1450.github.io/map/data_resources.html)
    
- Wednesday 8/20
    - [STA-330 Icebreaker Activity](https://remiller1450.github.io/s330s25/intro.html)