---
title: "STA-395 - Intro to Machine Learning (Fall '26)"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
---

$~$

Welcome to the website for **Sta-395, Introduction to Machine Learning**! To begin, you can find the course syllabus linked below:

- [Click here](syllabusML26.html) to view the course syllabus

You can locate course content by scrolling, or by using the navigation bar in the upper-left.

## Course Materials

Most class meetings involve both lecture and lab components. Topics are organized into units, which can be found below. The assignments and due-dates for a given week can be found below that week's course materials. Unless otherwise indicated, all assignments are to be submitted via Canvas by 11:59pm.

$~$

### Unit #1 - Concepts, Workflow, and Methods for Tabular Data

#### Week 0/1 - Introduction to Python and `sklearn`

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(knitr)
library(kableExtra)
library(dplyr)
# x <- cars[1:3,]
# urls <- c("stackoverflow.com", "stats.stackexchange.com", "homebrew.stackexchange.com")
# linkID <- c("link1", "link2", "link3")
# x$website <- paste0("[", linkID, "](http://", urls, ")")
# kable(x)

x = data.frame(Date = c("Th 8/28", "T 9/2", "Th 9/4"), 
               Lecture = c("[Introduction](ml25/intro.pdf)", 
                           "[KNN and Decision Trees](ml25/simple_models.pdf)",
                           "[Data Pre-processing](ml25/preproc.pdf)"),
               Lab = c("[Lab 1 - Crash Course in Python](ml25/Lab_1_F25.html)", 
                       "Finish Lab 1",
                       "[Lab 2 - Introduction to `sklearn`](ml25/Lab_2_F25.html)"),
               Resources = c(" ", " ", " "))
knitr::kable(x, format = "html") %>%
  kable_styling(bootstrap_options = c("hover"))
```

- Lab 1 is due Monday 9/8 at 11:59pm on Canvas
- Lab 2 is due Wednesday 9/10  at 11:59pm on Canvas

#### Week 2

Coming soon...

$~$

## Final Project 

Coming soon...




