---
title: "STA-395 - Introduction to Machine Learning (Spring '24)"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
---

$~$

Welcome to the website for **Sta-395, Introduction to Machine Learning**! To begin, you can find the course syllabus linked below:

- [Click here](syllabusML24.html) to view the course syllabus

You can locate course content by scrolling, or by using the navigation bar in the upper-left.

## Course Materials

Most class meetings involve both lecture and lab components. Topics are organized into units, which can be found below. Assignment submissions should be made via P-web following the instructions that are provided. Labs are generally due on Fridays at midnight, while homework is due at the start of the class session when we begin the next unit.

$~$

### Unit #1 

**Overview, Introductory Python, and Unsupervised Learning**:

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(knitr)
library(kableExtra)
library(dplyr)
# x <- cars[1:3,]
# urls <- c("stackoverflow.com", "stats.stackexchange.com", "homebrew.stackexchange.com")
# linkID <- c("link1", "link2", "link3")
# x$website <- paste0("[", linkID, "](http://", urls, ")")
# kable(x)

x = data.frame(Date = c("1/23", "1/25", "1/30", "2/1"), 
               Lecture = c("[Introduction and k-means](ml24/intro.pdf)", " ", "[Hierarchical clustering and DBSCAN](ml24/dbscan.pdf)", "Principal Components"),
               Lab = c("[Lab 1 - Python Foundations and k-means](ml24/intro_clustering.html)", "Continue Lab 1", "[Lab 2 - More Clustering](ml24/lab2_clustering.html)", "Lab 3 - Principal Components"))
kable(x) %>%
  kable_styling(bootstrap_options = c("hover"))
```

**Assignments**:

- Introduction to Python and $k$-means clustering lab (Lab 1) is due Friday 1/26 at 11:59pm
    - Please submit a Jupyter Notebook via P-web containing all code and written responses
- The clustering and outlier detection lab (Lab 2), as well as the principal components lab (Lab 3) are due Friday 2/2 at 11:59pm
    - Please submit a Jupyter Notebook via P-web containing all code and written responses
- [Homework 1](ml24/hw1.html) due Tuesday 2/6 at 1:00pm
    - Please submit a Jupyter Notebook via P-web containing all code and written responses

$~$

### Unit #2 

Coming Soon

$~$

## Midterm Exam

Information and study materials for the midterm exam will be posted here.

$~$

## Final Project 

Deadlines and information regarding the course project will be posted here at a later date.

$~$

## Supplemental Resources

**Unit #1**:

- [UW-Madison SSCC Python Data Wrangling tutorials (balanced)](https://sscc.wisc.edu/sscc/pubs/dwp/Python_Fundamentals.html)
- [Python Data Science Handbook Chapters 2,3,4 (more technical)](https://jakevdp.github.io/PythonDataScienceHandbook/)
- [Stefanie Molin's Pandas workshop tutorials 1, 2 (less technical)](https://github.com/stefmolin/pandas-workshop)

