---
title: "STA-230 - Introduction to Data Science (Fall 2023)"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
---

$~$

Welcome to the course website for Sta-230, Introduction to Data Science. To begin, you can find the course syllabus linked below:

- [Click here](syllabus230f23.html) to view the course syllabus

You can locate course content by scrolling, or by using the navigation bar in the upper left.  

*Note*: Some material may not be posted until we've reached that point in the course.

### Labs

Sta-230 uses a *workshop style* class format. This means that the majority of our class time will be devoted towards collaboratively working through guided lab activities. You should consult the syllabus for a more detailed description of lab procedures and expectations.

**Lab Topics and Links**:

- Introduction to `R`
    - [Lab 1 (intro to R, Part 1)](s230f23/intro.html)
    - [Lab 1 (Part 2)](s230f23/intro2.html)
        - Lab 1 (parts 1 and 2) due Thursday 8/31 by 11:59pm
        - Please submit your responses (to both parts) as *single document* created using R Markdown
    - [Optional Lab (hypothesis tests in R)](s230f23/ht.html) due Tuesday 9/5 by 11:59pm
- Data visualization
    - [Lab 2 (intro to `ggplot2`)](s230f23/ggplot.html)
    - [Lab 3 (effective data visualizations)](s230f23/ggplot2.html)
        - Lab 2 and 3 are due Thursday 9/7 by 11:59pm
- Data manipulation
    - [Lab 4 (reshaping with `tidyr`)](s230f23/tidyr.html)
    - [Lab 5 (manipulation with `dplyr`)](s230f23/dplyr.html)
    - [Lab 6 (merging and joining)](s230f23/joins.html)
        - Labs 4, 5, and 6 are due Thursday 9/21
        - Midterm #1 (take home) will occur after this unit (9/26)
    - [Optional Lab (files, function, and iteration)](s230f23/files.html) is due Tuesday 9/26
- Working with strings and dates
    - [Lab 7 (text processing with `stringr`)](s230f23/strings.html)
    - [Lab 8 (date/time processing with `lubridate`)](s230f23/dates.html)
        - Lab 7 and Lab 8 are due *Monday 10/9*
- Interactive data visualizations
    - [Lab 9 (interactive graphics with `plotly`)](s230f23/plotly.html)
    - [Lab 10 (maps with `leaflet` and `ggplot`)](s230f23/maps.html)
        - Labs 9 and 10 are due Tuesday 10/24 at 11:59pm
- R Shiny applications
    - [Lab 11 (intro to `shiny`)](s230f23/shiny.html)
        - Lab 11 is due Thursday 10/26 at 11:59pm
- Principal component analysis
    - [Lab 12 (PCA)](s230f23/pca.html)
        - Lab 12 is due Thursday 11/9 at 11:59pm
- Clustering
    - [Lab 13 (partitional clustering)](s230f23/clustering1.html)
    - [Lab 14 (hierarchical clustering)](s230f23/clustering2.html)
    - Labs 13 and 14 are due Tuesday 11/21 at 11:59pm
- Supervised Learning
    - [Lab 15 (regression)](s230f23/supervised1.html)
    - [Lab 16 (model evaluation using cross-validation)](s230f23/supervised2.html)
    - [Lab 17 (classification)](s230f23/supervised3.html)
    - [Optional lab (boosting and bagging)](s230f23/boost_bag.html)
        - Labs 15, 16, and 17 are due Friday 12/8 by 11:59pm

### Homework Assignments

Throughout the semester there will be 6-7 homework assignments:

- [Homework #1](s230f23/hw1.html)
    - [.Rmd Template](s230f23/hw1.zip)
    - Due date: Tuesday 9/5 by 11:59pm
- [Homework #2](s230f23/hw2.html)
    - Due date: *Sunday 9/24* by 11:59pm
- [Homework #3](s230f23/hw3.html)
    - Due date: Friday 10/13 by 11:59pm
- [Homework #4](s230f23/hw4.html)
    - Due date: Tuesday 10/31 by 11:59pm
- [Homework #5](s230f23/hw5.html)
    - Due date: Thursday 11/16 by 11:59pm
- [Homework #6](s230f23/hw6.html)
    - Due date: Thursday 11/30 by 11:59pm
- [Homework #7](s230f23/hw7.html)
    - Due date: Friday 12/8 by 11:59pm

### Projects

There will be 3 major projects during the semester. Details on each project will be posted no later than 2 weeks before the project's first deadline.

1. Data cleaning and visualization take-home (midterm #1)
    - Currently planned to be released on Monday 9/25 at noon and due Wednesday 9/27 by 11:59pm
    - There will be no class on Tuesday 9/26 to provide time for the take-home
    - [Practice take-home (from Spring 2023)](s230f23/takehome2.pdf)
2. [R Shiny application (midterm #2)](s230f23/rshiny_project.html)
    - Send a proposal via email by midnight on Tuesday 10/24
    - Plan to present your app on Tuesday 11/7
3. [Data analysis report (final)](s230f23/final_project.html)
    - Send a proposal via email by midnight on Tuesday 11/28

### Recommended Readings

The following readings are *recommended* in conjunction with the block of material they cover. They are intended to provide another perspective on the topics we'll cover:

- Introduction to R
    - [Ch 4 (R basics) - R for Data Science](https://r4ds.had.co.nz/workflow-basics.html)
    - [Ch 27 (R Markdown - R for Data Science)](https://r4ds.had.co.nz/r-markdown.html)
- Data Visualization
    - [Ch 3 (Data visualization) - R for Data Science](https://r4ds.had.co.nz/data-visualisation.html)
    - [Ch 2.1, 2.2, 2.3, 2.4 (Data visualization case study) - Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/ch-vizI.html)
    - [Ch 3 (ggplot) - Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/ch-vizII.html)
- Data Manipulation
    - [Ch 12 (Tidy data) - R for Data Science](https://r4ds.had.co.nz/tidy-data.html)
    - [Ch 4 (Data wrangling) - Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/ch-dataI.html)
    - [Ch 5 (Joins) - Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/ch-join.html)
    - [Ch 13 (Relational data) - R for Data Science](https://r4ds.had.co.nz/relational-data.html)   
- Working with strings and dates
    - [Ch 14 (Strings) - R for Data Science](https://r4ds.had.co.nz/strings.html)     
    - [Ch 17 (Dates and times) - R for Data Science](https://r4ds.had.co.nz/dates-and-times.html)
- Interactive Data Visualizations
    - [Ch 2.1 (Intro Plotly) - Interactive web-based data visualization with R, plotly, and shiny](https://plotly-r.com/overview.html#intro-plotly)
    - [Ch 17 (Maps and Geospatial data) - Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/ch-spatial.html#motivation-whats-so-great-about-geospatial-data)
- R Shiny
    - [Ch 14.4 (web apps with Shiny) - Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/ch-vizIII.html#sec:shiny)
- Principal Component Analysis
    - [Ch 12.1 and 12.2 (PCA) - Intro to Statistical Learning](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf)
- Clustering 
    - [Ch 12.4 (Clustering) - Intro to Statistical Learning](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf)
- Supervised Learning
    - [Intro to Statistical Learning, Ch 2.2 and 3.5 (kNN)](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf)
    - [Intro to Statistical Learning, Ch 8 (Decision Tree Models)](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf)
    - [Stanford's Intro to Statistical Learning video 5.2 (k-fold CV)](https://www.youtube.com/watch?v=AMfvd_hLssE&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=28)
    - [Stanford's Intro to Statistical Learning video 5.3 (CV the right and wrong way)](hhttps://www.youtube.com/watch?v=jgoa28FR__Y&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=29)
    - [Intro to Statistical Learning, Ch 4.2 and 4.3 (Logistic Regression)](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf)