---
title: "STA-230 - Introduction to Data Science (Fall 2022)"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
---

$~$

### Syllabus

Welcome to the course website for Sta-230, Introduction to Data Science. To begin, you can find the course syllabus linked below:

- [Click here](syllabus230f22.html) to view the course syllabus

You can locate course content by scrolling, or by using the navigation bar in the upper left.  

Please note: material will not be posted until we've reached that point in the course.

### Labs

Sta-230 uses a *workshop style* class format. This means that the majority of our class time will be devoted towards collaboratively working through guided lab activities. You should consult the syllabus for a more detailed description of procedures related to labs.

**Lab Topics and Links**:

- Introduction to `R`
    - [Lab #1 (8/26) - Intro to R (part 1)](s230f22/day1.html)
    - [Lab #2 (8/29 and 8/31) - Intro to R (part 2)](s230f22/intro2.html)
    - [Optional Lab - Hypothesis Testing in R](s230f22/intro_stat.html)
    - Labs 1 and 2 are due ~~Wednesday 8/31~~ Friday 9/2 by 11:59pm 
    - You can choose to submit the optional lab for 1 point of extra credit (due Friday 9/2 by 11:59pm, upload w/ your Lab 1 and 2 copies)
- Data visualization
    - [Lab #3 (9/2) - Intro to `ggplot2`](s230f22/ggplot.html)
    - [Lab #4 (9/5 and 9/7) - Data Visualization Principles](s230f22/ggplot2.html)
    - Labs 3 and 4 are due Friday 9/9 by 11:59pm 
- Data manipulation
    - [Lab #5 - Reshaping data with `tidyr`](s230f22/cleaning.html)
    - [Lab #6 - Wrangling data with `dplyr`](s230f22/cleaning2.html)
    - [Lab #7 - Merging and joining with `dplyr`](s230f22/cleaning3.html)
    - [Optional Lab - Functions, Iteration, and Files](s230f22/misc.html)
    - Labs 5, 6, and 7 are due Monday 9/19 by 11:59pm 
    - You can choose to submit the optional lab for 1 point of extra credit (due at the same time as Labs 5, 6, and 7)
- Working with strings
    - [Lab #8 - String processing with `stringr`](s230f22/strings.html)
    - Lab 8 is due Wednesday 9/21 by 11:59 pm 
- Interactive data visualizations
    - [Lab #9 - Intro to `plotly`](s230f22/plotly.html)
    - [Lab #10 - Making maps with `ggplot` and `leaflet`](s230f22/maps.html)
    - Labs 9 and 10 are due Monday 10/3 by 11:59pm
- Interactive web applications
    - [Lab #11 - Intro to R Shiny](s230f22/shiny.html)
    - Lab 11 is due Wednesday 10/5 by 11:59pm
- Principal component analysis
    - [Lab #12 - Principal component analysis](s230f22/pca.html)
    - Lab 12 is due Monday 10/31 by 11:59pm
- Clustering
    - [Lab #13 - Partitional methods](s230f22/clustering1.html)
    - [Lab #14 - Hierarchical methods](s230f22/clustering2.html)
    -  Labs 13 and 14 are due Monday 11/7 by 11:59pm 
- Modeling a numeric outcome
    - [Lab #15 - Linear regression and K-nearest neighbors](s230f22/numeric.html)
    - Lab #16 - Cross-validation and model evaluation
    - <span style="color: red;"> Due date TBD \span
- Modeling a categorical outcome
    - Lab #17 - Logistic regression
    - Lab #18 - Expressing model accuracy
- Tree-based models
- Variable selection and penalized regression

### Recommended Readings

The following readings are *recommended* in conjunction with the block of material they cover. While not required, it is my observation that students who seek to learn the course material from a variety of perspectives are most successful.

- Introduction to R
    - [Ch 4 (R basics) - R for Data Science](https://r4ds.had.co.nz/workflow-basics.html)
    - [Ch 27 (R Markdown - R for Data Science)](https://r4ds.had.co.nz/r-markdown.html)
- Data Visualization
    - [Ch 3 (Data visualization) - R for Data Science](https://r4ds.had.co.nz/data-visualisation.html)
    - [Ch 2.1, 2.2, 2.3, 2.4 (Data visualization case study) - Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/ch-vizI.html)
    - [Ch 3 (ggplot) - Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/ch-vizII.html)
- Data Manipulation
    - [Ch 12 (Tidy data) - R for Data Science](https://r4ds.had.co.nz/tidy-data.html)
    - [Ch 4 (Data wrangling) - Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/ch-dataI.html)
    - [Ch 5 (Joins) - Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/ch-join.html)
    - [Ch 13 (Relational data) - R for Data Science](https://r4ds.had.co.nz/relational-data.html)
- Working with Strings
    - [Ch 14 (Strings) - R for Data Science](https://r4ds.had.co.nz/strings.html)
- Interactive Data Visualizations
    - [Ch 2.1 (Intro Plotly) - Interactive web-based data visualization with R, plotly, and shiny](https://plotly-r.com/overview.html#intro-plotly)
    - [Ch 17 (Maps/Geospatial data) - Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/ch-spatial.html#motivation-whats-so-great-about-geospatial-data)
- R Shiny
    - [Ch 14.4 (Shiny) - Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/ch-vizIII.html#sec:shiny)
    - [Ch 17 (Shiny) - Interactive web-based data visualization with R, plotly, and shiny](https://plotly-r.com/linking-views-with-shiny.html)
- Dimension Reduction and PCA
    - [Ch 12.1 and 12.2 (PCA) - Intro to Statistical Learning](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf)
- Clustering
    - [Ch 12.4 (Clustering) - Intro to Statistical Learning](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf)
- Modeling a numeric outcome
    - [Ch 2.1 and 2.2 (Concepts in stat learning) - Intro to Statistical Learning](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf)
    - [Ch 3.1, 3.2, and 3.3 (linear regression) - Intro to Statistical Learning](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf)
- Modeling a categorical outcome
    - [Ch 4.1, 4.2, and 4.3 (Classification and logistic regression) - Intro to Statistical Learning](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf)
- Tree-based models
     - [Ch 8.1 and 8.2 (Decision trees and random forests) - Intro to Statistical Learning](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf)
- Penalized regression
     - [Ch 6.1, 6.2, and 6.4 (Variable selection and shrinkage methods) - Intro to Statistical Learning](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf)
     
### Homework Assignments

Throughout the semester there will be 6-7 homework assignments:

- [Homework #1](s230f22/hw1.html) 
    - Topics: Intro R, `ggplot2`, data visualization
    - [.Rmd Template](s230f22/hw1.zip)
    - Due date: Monday 9/5 at 11:59pm 
- [Homework #2](s230f22/hw2.html) 
    - Topics: ggplot2, reshaping, wrangling, merging and joining, string processing
    - [.Rmd Template](s230f22/hw2.zip)
    - Due date: Monday 9/19 at 11:59pm
- [Homework #3](s230f22/hw3.html) 
    - Topics: string processing, `plotly`, `leaflet`
    - Due date: Wednesday 10/5 at 11:59pm
- [Homework #4](s230f22/hw4.html)
    - Topics: Principal component analysis
    - Due date: Wednesday 11/2 at 11:59pm
- [Homework #5](s230f22/hw5.html)
    - Topics: Clustering 
    - <span style="color: red;"> Due date: Friday 11/11 at 11:59pm \span
- Homework #6
    - Topics: Modeling foundations, regression, k-nearest neighbors
- Homework #7
    - Topics: Modeling categorical outcomes, tree-based models

    
### Projects

There will be 3 projects throughout the semester. Tentative dates for these projects can be found below:

- [Project #1 - Data Visualization](s230f22/project1.html)
    - Friday 9/9 by 11:59pm - partners and proposals
    - Wednesday 9/21 and Friday 9/23 - in-class work sessions and meetings
    - Friday 9/23 by 11:59pm - post on P-web
    - Monday 9/26 by 11:59pm - post peer reviews on P-web
- [Project #2 - R Shiny](s230f22/project2.html)
    - Project sign-ups Friday 9/30
    - Presentations during class on Monday 10/10 and Monday 10/24
- Project #3 - Modeling and Data Analysis
    - Information coming soon

*Please note*: these projects do not contribute equally to your final grade. Project #1 is only 5% of your overall grade, making it worth only slightly more than a homework assignment (each worth ~3%)