---
title: "STA-230 - Introduction to Data Science (Spring 2022)"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
---

$~$

### Syllabus

Welcome to the course website for Sta-230, Introduction to Data Science. To begin, you can find the course syllabus linked below:

- [Click here](syllabus230s23.html) to view the course syllabus

You can locate course content by scrolling, or by using the navigation bar in the upper left.  

Please note: material will not be posted until we've reached that point in the course.

### Labs

Sta-230 uses a *workshop style* class format. This means that the majority of our class time will be devoted towards collaboratively working through guided lab activities. You should consult the syllabus for a more detailed description of lab procedures and expectations.

**Lab Topics and Links**:

- Introduction to `R`
- Data visualization
- Data manipulation
- Working with strings
- Interactive data visualizations
- R Shiny applications
- Principal component analysis
- Clustering
- Modeling a numeric outcome
- Modeling a categorical outcome

### Recommended Readings

The following readings are *recommended* in conjunction with the block of material they cover. They are intended to provide another perspective on the topics we'll cover:

- Introduction to R
    - [Ch 4 (R basics) - R for Data Science](https://r4ds.had.co.nz/workflow-basics.html)
    - [Ch 27 (R Markdown - R for Data Science)](https://r4ds.had.co.nz/r-markdown.html)
- Data Visualization
    - [Ch 3 (Data visualization) - R for Data Science](https://r4ds.had.co.nz/data-visualisation.html)
    - [Ch 2.1, 2.2, 2.3, 2.4 (Data visualization case study) - Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/ch-vizI.html)
    - [Ch 3 (ggplot) - Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/ch-vizII.html)
- Data Manipulation
    - [Ch 12 (Tidy data) - R for Data Science](https://r4ds.had.co.nz/tidy-data.html)
    - [Ch 4 (Data wrangling) - Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/ch-dataI.html)
    - [Ch 5 (Joins) - Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/ch-join.html)
    - [Ch 13 (Relational data) - R for Data Science](https://r4ds.had.co.nz/relational-data.html)
- Working with Strings
    - [Ch 14 (Strings) - R for Data Science](https://r4ds.had.co.nz/strings.html)
- Interactive Data Visualizations
    - [Ch 2.1 (Intro Plotly) - Interactive web-based data visualization with R, plotly, and shiny](https://plotly-r.com/overview.html#intro-plotly)
    - [Ch 17 (Maps/Geospatial data) - Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/ch-spatial.html#motivation-whats-so-great-about-geospatial-data)
- R Shiny
    - [Ch 14.4 (R Shiny) - Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/ch-vizIII.html#sec:shiny)
    - [Ch 17 (Shiny) - Interactive web-based data visualization with R, plotly, and shiny](https://plotly-r.com/linking-views-with-shiny.html)
- Dimension Reduction and PCA
    - [Ch 12.1 and 12.2 (PCA) - Intro to Statistical Learning](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf)
- Clustering
    - [Ch 12.4 (Clustering) - Intro to Statistical Learning](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf)
- Modeling a numeric outcome
    - [Ch 2.1 and 2.2 (Concepts in stat learning) - Intro to Statistical Learning](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf)
    - [Ch 3.1, 3.2, and 3.3 (linear regression) - Intro to Statistical Learning](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf)
- Modeling a categorical outcome
    - [Ch 4.1, 4.2, and 4.3 (Classification and logistic regression) - Intro to Statistical Learning](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf)
- Tree-based models
     - [Ch 8.1 and 8.2 (Decision trees and random forests) - Intro to Statistical Learning](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf)
- Penalized regression
     - [Ch 6.1, 6.2, and 6.4 (Variable selection and shrinkage methods) - Intro to Statistical Learning](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf)
     
### Homework Assignments

Throughout the semester there will be 6-7 homework assignments:

- [Homework #1](s230s23/hw1.html)
    - Due date: TBD
    
### Projects

There will be 3 major projects during the semester. Details on each project will be posted no later than 2 weeks prior to the project's first deadline.

1. Data cleaning and visualization take-home
2. R Shiny application
3. Data analysis (final)