---
title: "Sta-209 Applied Statistics (Spring 2020)"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
---

### Schedule and Syllabus

Welcome to course website for Sta-209, Applied Statistics!  On this page you can find all materials we'll use throughout the semester, starting with the syllabus linked below:

- [Click here](s209s20/syllabus209s20.html) to view the course syllabus

You can find course content by scrolling, or by using the navigation bar in the upper left. Please note:

1. I will occasionally not post a lecture in advance if it contains some type of "surprise" that I don't want you to see ahead of time.
2. Links may not become active until we've reached the appropriate point in the course, so if you get a "404 page not found" error it is likely because we haven't reached that topic yet.


### Lectures

- [Introduction](s209s20/intro_h.pdf) (Wed 1/22)
- [Descriptive Statistics](s209s20/sum_h.pdf) (Fri 1/24)
- [Correlation and Regression](s209s20/cr_h.pdf) (Wed 1/29)
- Populations and Samples (Fri 1/31)
- Causation, Confounding Variables, and Randomized Experiments
- Interval Estimation Part I (Sampling Distributions)
- Interval Estimation Part II (Confidence Intervals)
- Interval Estimation Part III (Normal Approximations)
- Interval Estimation Part IV (The $t$-distribution)
- Hypothesis Testing Part I (Null Distributions and p-values)
- Hypothesis Testing Part II (Testing Errors, Power, and Multiple Comparisons)
- Hypothesis Testing Part III (Normal Approximations)
- Hypothesis Testing Part IV (The $t$-test)
- Outliers, Transformations, and Non-parametric Tests
- Chi-Squared Tests
- Analysis of Variance (ANOVA)
- Regression Modeling Part I (Simple Linear Regression and ANOVA)
- Regression Modeling Part II (Multiple Regression)

```{r, include = FALSE, eval = FALSE}
#-	Intro
#	Keep as-is
#-	Pop and Samples
#	Keep as-is
#-	Do Lab #1 (descriptive stats, update lab)
#-	Correlation, association, and causation
#	Need to create
#-	Do Lab #2 (Florida death penalty, update but mostly good)
#-	Randomized Experiments
#	Mostly okay
#-	Interval Estimation Part I (Sampling Distributions)
#	Need to make/update
#-	Interval Estimation Part II (Bootstrapping)
#	Need to make/update
#-	Lab #3 (bootstrapping, mostly okay)
#-	Interval Estimation Part III (Normal Approximations)
#	Need to make/update
#	1 prop -> 2 prop -> 1 mean -> 2 means, but quick
#-	Lab #4 (confidence intervals, need to make, include confounding in there and maybe intro to using intervals to do a test?)
#-	Hypothesis Testing Part I (Null Distributions and p-values)
#	Mostly good, might need to update
```


### Labs

Labs and due dates are listed below.  Please note that during or after a lab you have the opportunity to report on the participation of your group members using [this anonymous form](https://forms.gle/wNWRFMbbra8oK4LJ8).

- [Lab #1 - Descriptive Statistics and Graphs](s209s20/Lab1.html) (Fri 1/24 and Mon 1/27)
    - due date: Wednesday 1/29
- Lab #2 - Confounding Variables and Stratification (Mon 2/3)
    - due date: TBD
- Lab #3 - Bootstrapping
    - due date: TBD
- Lab #4 - Confidence Intervals
    - due date: TBD
- Lab #5 - Randomization Testing
    - due date: TBD
- Lab #6 - A/B Testing
    - due date: TBD
- Lab #7 - Hypothesis Testing
    - due date: TBD
- Lab #8 - Chi-Squared Testing and More
    - due date: TBD
- Lab #9 - Analysis of Variance and More
    - due date: TBD
- Lab #10 - Regression
    - due date: TBD

### Recommended Readings

The readings listed below are *recommended* prior to the date indicated. It has been my observation that students who complete these readings have been the most successful.

- Ch 1.1 (Wed 1/22)
- Ch 2.1, 2.2, 2.3 (Fri 1/24)
- Ch 2.4, 2.5 (Mon 1/27)
- Ch 2.6 (Wed 1/29)
- Ch 1.2 (Fri 1/31)
    
### Homeworks

Homework is generally due *at the start of class* every Friday (with a few exceptions near exams). You can always turn-in an assignment early, but if you'd like to request an extension to turn-in an assignment late you must contact me at least 24-hours prior to the posted deadline *and* you submit the assignment electronically (a scanned or typed version sent via email).  

- HW #1: 1.15, 1.16, 1.22, 2.20, 2.66, 2.116 2.117, 2.118
    - Data needed for some exercises is [available here](http://www.lock5stat.com/datapage.html)
    - due date: Friday 1/31
- HW #2: TBD
    - due date: TBD
- HW #3: TBD
    - due date: TBD
- HW #4: TBD
    - due date: TBD
- HW #5: TBD
    - due date: TBD
- HW #6: TBD
    - due date: TBD
- HW #7: TBD
    - due date: TBD
- HW #8: TBD
    - due date: TBD
- HW #9: TBD
    - due date: TBD
- HW #10: TBD
    - due date: TBD
- HW #11: TBD
    - due date: TBD

### Announcements and Other Materials 

- Please complete the survey at [this link](https://forms.gle/yd8MMuTxw7kcJ5nL7) sometime during the first week of class.  This helps me get to know you, and completing it will contribute a small amount towards your participation score for the semester.
- Exam #1 is tentatively planned for Friday 2/21
    - Study materials will be posted on p-web at least 1 week prior to the exam
    
### Datasets

- [Happy Planet](https://remiller1450.github.io/data/HappyPlanet.csv)
    - This dataset was assembled by [The Happy Planet Index](http://happyplanetindex.org/) using data from a global survey that asks respondents questions about how they feel their lives are going. It documents the health and well-being of the inhabitants of various nations around the world. 
- [Mass Shootings](https://remiller1450.github.io/data/MassShootings.csv)
    - This dataset was originally assembled in response to the movie theater shooting in Aurora Colorado by [Mother Jones](https://en.wikipedia.org/wiki/Mother_Jones_(magazine)), a liberal news organization.  It documents shootings in the United States where a lone gunman (with a few exceptions involving two shooters) killed at least four individuals (not including themselves) at a single location (with a few exceptions involving multiple locations within a short period). Variables include: demographic characteristics of the shooter, information on when/where the shooting occurred, information on the number of victims, and information about the mental health status of the shooter.
- [Death Penalty Sentencing](https://remiller1450.github.io/data/DeathPenaltySentencing.csv)
    - This dataset comes from a [widely cited study](https://chicagounbound.uchicago.edu/cgi/viewcontent.cgi?article=12039&context=journal_articles) on racially biased sentencing in the Florida court system during the 1970s. Researchers collected data on all murders that took place during a felony committed in the state of Florida between 1972 and 1977.  They record the race of the victim and the offender, as well as whether the offered was sentenced to the death penalty.
- [Infant Heart Surgery](https://remiller1450.github.io/data/InfantHeart.csv)
    - This dataset contains the results of a randomized experiment conducted by surgeons at Harvard Medical School to compare a "low-flow bypass" and "circulatory arrest" surgical approaches in the treatment of infants born with congenital heart defects. The outcomes recorded are Psychomotor Development Index (PDI), a composite score measuring physiological development, with higher scores indicating greater development, and Mental Development Index (MDI), a composite score measuring mental development, with higher scores indicating greater development. 
- [San Francisco Mall Shoppers](https://remiller1450.github.io/data/SF_Shoppers.csv)
    - In 1987, Impact Resources Inc. surveyed 9409 shopping mall customers in the San Francisco Bay area (San Francisco, Oakland, and San Jose).  This dataset contains the responses of 6876 shoppers who completed the survey.  It includes demographic characteristics such as: age, sex, income, marital status, education, occupation, household size, home type, and ethnicity.
- [Lead IQ](https://remiller1450.github.io/data/LeadIQ.csv)    
    - CDC researchers collected data in El Paso Texas from samples of children aged 3-15 living near (within 1 mile) and far (more than 1 mile away) from a local lead smelter.  This dataset documents the dependent variable, age-adjusted IQ score, for a subset of those children.  These data were obtained from the textbook: *Fundamentals of Biostatistics* by B. Rosner.
- [Wetsuits](https://remiller1450.github.io/data/Wetsuits.csv)  
    - This dataset contains 1500m swim velocities for 12 competitive swimmers when wearing a specially designed wetsuit and without the wetsuit. These data were obtained from the [Lock5stat data page](http://www.lock5stat.com/datapage.html).
- [Professor Salaries](https://remiller1450.github.io/data/Salaries.csv)
    - This dataset contains 9-month academic year salaries for faculty members at a major United States university.  In addition to salaries from the 2008-09 academic year, the dataset contains de-identified documentation of the sex, rank, discipline, and experience of each faculty member. These data were obtained from the [carData `R` package](https://cran.r-project.org/web/packages/carData/index.html).
- [Police Killings](https://remiller1450.github.io/data/PoliceKillings.csv)
    - This data originates from the FiveThirtyEight article [Where Police Have Killed Americans in 2015](https://fivethirtyeight.com/features/where-police-have-killed-americans-in-2015/).  It contains demographic and geographic information on everyone killed by the police in the year 2015, including the person's name, age, race, gender, cause of death, whether the person was armed.  It was merged to include the poverty, unemployment, and college education rates of the census tract where the killing took place.
- [Golden State Warriors](https://remiller1450.github.io/data/GSWarriors.csv)
    - This dataset documents each of the 82 games in the record setting 2015-16 Golden State Warriors season. It was obtained from [Basketball Reference](https://www.basketball-reference.com/).
- [TSA Claims](https://remiller1450.github.io/data/TSA_Claims.csv) 
    - The Transport Security Administration (TSA) is an agency within the US Department of Homeland Security that has authority of the safety and security of travel in the United States.  This dataset documents claims made by travelers against the TSA between 2003 and 2008, including information of the claim type, claim amount, and whether it was approved, settled, or denied.
- [Tailgating and Drug Use](https://remiller1450.github.io/data/Tailgating.csv) 
    - Participants were recruited based upon their self-reported drug use and asked to follow an erratically behaving lead vehicle as part of a driving simulator experiment under the working hypothesis that regular users of certain drugs would exhibit more risky driving behavior.  The data were derived from a study conducted by the National Advanced Driving Simulator organization.
- [Colleges](https://remiller1450.github.io/data/CollegeData.csv)
    - These data come "The College Scorecard", a government run database containing information on all degree-granting higher education institutions.  This dataset are a subset of the Scorecard's 2018 dataset, they include only small colleges (1000-5000 students) that primarily award bachelors degrees and require the ACT for admission. 
- [Tips](https://remiller1450.github.io/data/Tips.csv) 
    - These data were recorded by a waiter in national chain restaurant located in a suburban shopping mall in the early 1990s. The data document various aspects of each table served by the waiter, including the total bill, tip, size of the party, time of day, day of the week, and whether the party included a smoker.  The data were originally obtained from the textbook: *Interactive and Dynamic Graphics for Data Analysis: With R*
- [Breast Cancer Survival](https://remiller1450.github.io/data/Breast_Cancer_Data.csv)
    - Description to be added
