---
title: "Sta-230 (Fall 2019)"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

### Schedule and Syllabus

Welcome to Sta-230, Introduction to Data Science!  On this page you can find all of the materials we'll use this semester, starting with the syllabus linked below:

- [Click here](syllabus230f19.html) to view the course syllabus

To see when and how we'll use these materials please visit the schedule page linked below:

- [Click here](tabs230f19.html) to view the course schedule

You can find course content in the sections below.  Please note:

1. Links may not become active until we've reached the appropriate point in the course, so if you get a "404 page not found" error it is because haven't gotten to that topic yet.
2. As a data scientist you should realize that it is difficult to predict far into the future, so some details on this page might be subject to change as we progress through the semester.

### Labs

- [NYPD Activity](s230f19/Using_Data.html)
- [Intro to R](s230f19/Intro_to_R.html)
- [Tidy Data with `tidyr`](s230f19/Tidy_Data.html)
- [Data Wrangling with `dplyr`](s230f19/Data_Wrangling.html)
- [Data Visualization with `ggplot2`](s230f19/ggplot.html)
- [Interactive Visualization with `plotly`](s230f19/plotly.html)
- [Merging and Joining with `dplyr`](s230f19/merging.html)
- [Making Maps with `leaflet`](s230f19/maps.html)
- [String Processing with `stringr`](s230f19/stringr.html)
- [Principal Components Analysis](s230f19/pca.html)
- Clustering
- Model Building with `caret` (numeric outcomes)
- Model Building with `caret` (binary outcomes)
- Model Building with `caret` (categorical outcomes)
- Black Box Models in `caret`

### Presentations

- [Summary Statistics (Intro Stats Review)](s230f19/summaries_pres.html)
- [The Simple-to-Complex Principle](s230f19/simple_complex.html)
- [Variable Transformations](s230f19/features.html)
- [Smoothing](s230f19/smoothing.html)
- [Density Estimation](s230f19/density.html)
- [Visualization Principles and Examples](s230f19/viz.html)
- [Intro to R Shiny](s230f19/shiny.html)
- [Principal Components Analysis (part I)](s230f19/pca_pres1.html)
- [Principal Components Analysis (part II)](s230f19/pca_pres2.html)
- Clustering (part I)
- Clustering (part II)
- Linear Regression and Variants
- Cross-validation
- Logistic Regression and Variants
- Accuracy, Kappa, Sensitivity, Specificity, and ROC curves
- k-Nearest Neighbors and Trees
- Black Box Models

### Group Lab Assignments

- Lab Submission #1 (due Tuesday 9/10)
    - All questions from the [Intro to R](s230f19/Intro_to_R.html) and [Tidy Data](s230f19/Tidy_Data.html) labs
- Lab Submission #2 (due Tuesday 9/17)
    - All questions from the [Data Wrangling](s230f19/Data_Wrangling.html) and [Data Visualization](s230f19/ggplot.html) labs
- Lab Submission #3 (due Tuesday 9/24)
    - All questions from the [Interactive Visualization](s230f19/plotly.html) and [Merging and Joining](s230f19/merging.html) labs
    - These questions should be submitted as a single HTML file generated using R Markdown
- Lab Submission #4 (due Tuesday 10/1)
    - All questions from the [Making Maps](s230f19/maps.html) and [String Processing](s230f19/stringr.html) labs
    - These questions should be submitted as a single HTML file generated using R Markdown
- Lab Submission #5 (due *Monday* 10/21)
    - All questions from the [Principal Components Analysis](s230f19/pca.html) lab
- Lab Submission #6 (due TBD)
    - All questions from the Clustering lab
- Lab Submission #7 (due TBD)
    - All questions from the Supervised Learning with `caret` (numeric outcomes) lab
- Lab Submission #8 (due TBD)
    - All questions from the Supervised Learning with `caret` (binary outcomes) lab
- Lab Submission #9 (due TBD)
    - All questions from the Supervised Learning with `caret` (categorical outcomes) lab                     
    
### Individual Problem Sets

- [Problem Set #1](s230f19/f19_hw1.html) (due Friday 9/13)
     - [R Markdown Template](s230f19/f19_hw1.Rmd)
     - [Raw .Rmd File](https://raw.githubusercontent.com/remiller1450/remiller1450.github.io/master/s230f19/f19_hw1.Rmd)
- [Problem Set #2](s230f19/f19_hw2.html) (due Friday 9/27)
    - [R Markdown Template](s230f19/f19_hw2.Rmd)
    - [Raw .Rmd File](https://raw.githubusercontent.com/remiller1450/remiller1450.github.io/master/s230f19/f19_hw2.Rmd)
- [Problem Set #3](s230f19/f19_hw3.html) (due Friday 11/1)
    - You should submit a compiled HTML file documenting your code, output, and written responses to the questions contained in the assignment document linked above
    - In an earlier version of this assignment some questions were incorrectly numbered, this has now been fixed
- Problem Set #4 (due TBD)
- Problem Set #5 (due TBD)



### Projects

- Midterm Project
    - [Assignment Link](s230f19/f19midterm.html)
    - [Meetings](s230f19/f19mid_times.html)
    - Presentations: Tuesday 10/15 and Thursday 10/17
    - Final Submission: Friday 10/18
- Final Project
    - Assignment Link (coming soon)
    - Meetings: Tuesday 12/10 and Thursday 12/15
    - Presentations: 2-5pm on Tuesday 12/17
    - Paper and Code: Friday 12/20 before 5:00pm

### Other Resources

- [R FAQ and Common Errors](s230f19/R_FAQ_Errors.html)
- [Project Data Sources and Topic Ideas](project_ideas.html)