---
title: "Sta-209 Applied Statistics (Fall 2019)"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
---

### Schedule and Syllabus

Welcome to Sta-209, Applied Statistics!  On this page you can find all of the materials we'll use during the semester, starting with the syllabus linked below:

- [Click here](syllabus209f19.html) to view the course syllabus

To see when and how we'll use these materials please visit the schedule page linked below:

- [Click here](tabs209f19.html) to view the course schedule

You can find course content by scrolling, or by using the navigation bar in the upper left. Please note:

1. Occasionally I will not post a lecture in advance, this is usually because it contains some type of "surprise" that I don't want you to see ahead of time.
2. Links may not become active until we've reached the appropriate point in the course, so if you get a "404 page not found" error it is likely because haven't gotten to that topic yet.
3. Predicting far into the future can be inaccurate, so some details like due dates are subject to change as we get closer to a topic/assignment. You should consult the schedule page to see official due dates.


### Lectures

- [Introduction](s209f19/intro_h.pdf)
- [Summarizing Data](s209f19/sum_h.pdf)
- [Populations and Samples](s209f19/sampling_h.pdf)
- [Causation, Confounding Variables, and Randomized Experiments](s209f19/random_h.pdf)
- [Interval Estimation Part I (Sampling Distributions)](s209f19/sampling_dist_h.pdf)
- [Interval Estimation Part II (Confidence Intervals)](s209f19/confidence_h.pdf)
- [Interval Estimation Part III (Normal Approximations)](s209f19/normal1.pdf)
- [Interval Estimation Part IV (The $t$-distribution)](s209f19/normal2.pdf)
- [Hypothesis Testing Part I (Null Distributions and p-values)](s209f19/ht1_h.pdf)
- [Hypothesis Testing Part II (Testing Errors, Power, and Multiple Comparisons)](s209f19/ht2_h.pdf)
- [Hypothesis Testing Part III (Normal Approximations)](s209f19/ht3_h.pdf)
- [Hypothesis Testing Part IV (The $t$-test)](s209f19/ht4_h.pdf)
- [Outliers, Transformations, and Non-parametric Tests](s209f19/outliers_h.pdf)
- [Chi-Squared Tests](s209f19/chisq_h.pdf)
- [Contingency Tables](s209f19/tabs_h.pdf)
- [Analysis of Variance (ANOVA)](s209f19/anova_h.pdf)
- Regression Part I (Simple Linear Regression)
- Regression Part II (Multiple Regression)
- Regression Part III (two-way ANOVA)
- Regression Part IV (Logistic Regression)

```{r, include = FALSE, eval = FALSE}
#-	Intro
#	Keep as-is
#-	Pop and Samples
#	Keep as-is
#-	Do Lab #1 (descriptive stats, update lab)
#-	Correlation, association, and causation
#	Need to create
#-	Do Lab #2 (Florida death penalty, update but mostly good)
#-	Randomized Experiments
#	Mostly okay
#-	Interval Estimation Part I (Sampling Distributions)
#	Need to make/update
#-	Interval Estimation Part II (Bootstrapping)
#	Need to make/update
#-	Lab #3 (bootstrapping, mostly okay)
#-	Interval Estimation Part III (Normal Approximations)
#	Need to make/update
#	1 prop -> 2 prop -> 1 mean -> 2 means, but quick
#-	Lab #4 (confidence intervals, need to make, include confounding in there and maybe intro to using intervals to do a test?)
#-	Hypothesis Testing Part I (Null Distributions and p-values)
#	Mostly good, might need to update
```


### Labs

- [Lab #1 - Descriptive Statistics and Graphs](s209f19/Lab1.html)
    - due date: Friday 9/6
- [Lab #2 - Confounding Variables and Stratification](s209f19/Lab2.html)
    - due date: Wednesday 9/11
- [Lab #3 - Bootstrapping](s209f19/Lab3.html)
    - due date: Friday 9/20
- [Lab #4 - Confidence Intervals](s209f19/Lab4.html)
    - due date: Monday 9/30
- [Lab #5 - Randomization Testing](s209f19/Lab5.html)
    - due date: Friday 10/11
- [Lab #6 - A/B Testing](s209f19/Lab6.html)
    - due date: Monday 10/28
- [Lab #7 - Hypothesis Testing](s209f19/Lab7.html)
    - due date: Monday 11/4
- [Lab #8 - Chi-Squared Testing and More](s209f19/Lab8.html)
    - due date: Wednesday 11/13
    - Please contact me regarding possible extensions, I'd also like for you to have time to study for Exam 2
- Lab #9 - Analysis of Variance
    - due date: TBD
- Lab #10 - Regression
    - due date: TBD

### Datasets

- [Happy Planet](https://remiller1450.github.io/data/HappyPlanet.csv)
    - This dataset was assembled by [The Happy Planet Index](http://happyplanetindex.org/) using data from a global survey that asks respondents questions about how they feel their lives are going. It documents the health and well-being of the inhabitants of various nations around the world. 
- [Mass Shootings](https://remiller1450.github.io/data/MassShootings.csv)
    - This dataset was originally assembled in response to the movie theater shooting in Aurora Colorado by [Mother Jones](https://en.wikipedia.org/wiki/Mother_Jones_(magazine)), a liberal news organization.  It documents shootings in the United States where a lone gunman (with a few exceptions involving two shooters) killed at least four individuals (not including themselves) at a single location (with a few exceptions involving multiple locations within a short period). Variables include: demographic characteristics of the shooter, information on when/where the shooting occurred, information on the number of victims, and information about the mental health status of the shooter.
- [Death Penalty Sentencing](https://remiller1450.github.io/data/DeathPenaltySentencing.csv)
    - This dataset comes from a [widely cited study](https://chicagounbound.uchicago.edu/cgi/viewcontent.cgi?article=12039&context=journal_articles) on racially biased sentencing in the Florida court system during the 1970s. Researchers collected data on all murders that took place during a felony committed in the state of Florida between 1972 and 1977.  They record the race of the victim and the offender, as well as whether the offered was sentenced to the death penalty.
- [Infant Heart Surgery](https://remiller1450.github.io/data/InfantHeart.csv)
    - This dataset contains the results of a randomized experiment conducted by surgeons at Harvard Medical School to compare a "low-flow bypass" and "circulatory arrest" surgical approaches in the treatment of infants born with congenital heart defects. The outcomes recorded are Psychomotor Development Index (PDI), a composite score measuring physiological development, with higher scores indicating greater development, and Mental Development Index (MDI), a composite score measuring mental development, with higher scores indicating greater development. 
- [San Francisco Mall Shoppers](https://remiller1450.github.io/data/SF_Shoppers.csv)
    - In 1987, Impact Resources Inc. surveyed 9409 shopping mall customers in the San Francisco Bay area (San Francisco, Oakland, and San Jose).  This dataset contains the responses of 6876 shoppers who completed the survey.  It includes demographic characteristics such as: age, sex, income, marital status, education, occupation, household size, home type, and ethnicity.
- [Lead IQ](https://remiller1450.github.io/data/LeadIQ.csv)    
    - CDC researchers collected data in El Paso Texas from samples of children aged 3-15 living near (within 1 mile) and far (more than 1 mile away) from a local lead smelter.  This dataset documents the dependent variable, age-adjusted IQ score, for a subset of those children.  These data were obtained from the textbook: *Fundamentals of Biostatistics* by B. Rosner.
- [Wetsuits](https://remiller1450.github.io/data/Wetsuits.csv)  
    - This dataset contains 1500m swim velocities for 12 competitive swimmers when wearing a specially designed wetsuit and without the wetsuit. These data were obtained from the [Lock5stat data page](http://www.lock5stat.com/datapage.html).
- [Professor Salaries](https://remiller1450.github.io/data/Salaries.csv)
    - This dataset contains 9-month academic year salaries for faculty members at a major United States university.  In addition to salaries from the 2008-09 academic year, the dataset contains de-identified documentation of the sex, rank, discipline, and experience of each faculty member. These data were obtained from the [carData `R` package](https://cran.r-project.org/web/packages/carData/index.html).
- [Police Killings](https://remiller1450.github.io/data/PoliceKillings.csv)
    - This data originates from the FiveThirtyEight article [Where Police Have Killed Americans in 2015](https://fivethirtyeight.com/features/where-police-have-killed-americans-in-2015/).  It contains demographic and geographic information on everyone killed by the police in the year 2015, including the person's name, age, race, gender, cause of death, whether the person was armed.  It was merged to include the poverty, unemployment, and college education rates of the census tract where the killing took place.
- [Golden State Warriors](https://remiller1450.github.io/data/GSWarriors.csv)
    - This dataset documents each of the 82 games in the record setting 2015-16 Golden State Warriors season. It was obtained from [Basketball Reference](https://www.basketball-reference.com/).
    
### Homeworks

- HW #1: 1.15, 1.16, 1.22, 2.20, 2.66, 2.116 2.117, 2.118
    - Data needed for some exercises is [available here](http://www.lock5stat.com/datapage.html)
    - due date: Friday 9/6
- HW #2: 1.40, 1.41, 1.42, 1.43, 1.44, 1.45, 1.60, 1.91, 1.92, 1.100, 1.103 
    - No explanations are necessary for 1.40 - 1.45
    - due date: Friday 9/13
- HW #3: 3.25, 3.26, 3.29, 3.58, 3.64 3.93, 3.94, 3.102, 3.125, 3.130
    - due date: Friday 9/20
- HW #4: 5.43, 5.52, 6.20, 6.26, 6.30, 6.96, 6.97, 6.98
    - due date: Friday 9/27
    - A mistake in the original assignment included problems 6.143, 6.144, which have since been removed. You aren't responsible for these questions.
- HW #5: 6.143, 6.148, 6.195, 6.196, 6.206
    - due date: *Wednesday* 10/2
- HW #6: 4.16, 4.18, 4.65, 4.66, 4.68, 4.101, 4.102, 4.113, 4.114 
    - due date: Friday 10/11
- HW #7: 4.144, 4.145, 6.56, 6.57, 6.60, 6.163, 6.164, 6.165 
    - due date: Friday 10/18
- HW #8: 6.121, 6.122, 6.215, 6.216, 6.250, 6.256, [additional questions #1 and #2](s209f19/f19s209hw8.html)
    - due date: Friday 11/1
- HW #9: 7.13, 7.20, 7.26, 7.27, 7.43, 7.44, 7.46
    - due date: Friday 11/8
- HW #10: 8.8, 8.15, 8.16, 8.17, 8.18, 8.32
    - due date: Friday 11/22
- HW #11: TBD
    - due date: *Monday* 12/2


### Announcements and Other Materials 

- Exam #1 will be Friday 10/4 during class
    - Some study materials are posted on p-web
- Details of the Final Project are now finalized, please check out the [Final Project Assignment Sheet link](s209f19/project209.html)
    - The first intermediate deadline for the project is on Monday 10/28 (deciding group members)
    - The second intermediate deadline for the project is on Monday 11/4 (project proposal)
    - The third deadline for the project is Monday 11/25 (cleaned dataset and data dictionary)
- Exam #2 will be Friday 11/15 during class
    - Some study materials are posted on p-web
    - I will out of town during the week of 11/11-11/15 with limited time to respond to emails, so please spread out your studying and ask your questions earlier rather than later.
    - On *Wednesday 11/13* I will have a practice exam (and solutions) for to you to work in class. 
- Exam #3 (the final exam) will be during the designated final exam time
    - For Section-02 (the 10-11:20am section) this is Wed 12/18 from 9am-noon
    - For Section-03 (the 1-2:20pm section) this is Fri 12/20 2-5pm (sorry the college decides this, not me)
