---
title: "Sta-395 Applied Data Science (Spring 2020)"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
---

### Syllabus

Welcome to course website for Sta-395 (cross-listed as Mat-395), Applied Data Science!  On this page you can information on the course, starting with the syllabus linked below:

- [Click here](syllabus395s20.html) to view the course syllabus

### Materials

- [Icebreaker activity](s395s20/First_day.html) (1/21)
    - [Dataset](https://remiller1450.github.io/data/GradAdm.csv)
    - [Debrief](s395s20/First_day_debrief.html)
- [Organizational structures, workflow, and project management](s395s20/ds_proj_manage.pdf) (1/23)
    - [The many "pipelines" and "life-cycles"](s395s20/ds_proj_pipe.pdf)
- Data ethics (1/28)
    - [Assignment description](s395s20/data_ethics_assign.html)
    - [Case Study #1](https://aiethics.princeton.edu/wp-content/uploads/sites/587/2018/10/Princeton-AI-Ethics-Case-Study-1.pdf)
    - [Case Study #2](https://aiethics.princeton.edu/wp-content/uploads/sites/587/2018/10/Princeton-AI-Ethics-Case-Study-2.pdf)
    - [Case Study #3](https://aiethics.princeton.edu/wp-content/uploads/sites/587/2018/10/Princeton-AI-Ethics-Case-Study-3.pdf)
    - [Case Study #4](https://aiethics.princeton.edu/wp-content/uploads/sites/587/2018/10/Princeton-AI-Ethics-Case-Study-4.pdf)
- Goal setting (1/30)
    - [Guidelines](s395s20/ds_goals.html)
- [First round goals](s395s20/goals_1_30.html) (1/30)
- [Second round goals](s395s20/goals_2_13_20.html) (2/13 and 2/20)
- [Third round goals](s395s20/goals_3_5_20.html) (2/27 and 3/5)

### Assignments

- [Project reflection](s395s20/proj_pref.html)
    - Due Sunday 1/26 by 11:59 pm
    - [Click here](s395s20/sta395_topics.html) to view project descriptions
- [Data ethics](s395s20/data_ethics_assign.html)
    - To be shared Tuesday 1/28 during class
- [Guidelines for bi-weekly progress briefings](s395s20/prog_guidelines.html)
- [Guidelines for bi-weekly advisor assessments](s395s20/adv_guidelines.html)
- Guidelines for midterm peer assessments
    - [Peer assessment #1](s395s20/peer_guidelines1.html) (due Monday 2/24 by 9:00am)
- Guidelines for project take-over memo and presentation
- Guidelines for executive summary
- Guidelines for technical report

### Important Dates

- Tuesday 2/11 - First progress meetings for Groups #1 and #2 during class
- Tuesday 2/18 - First progress meetings for Group #3 and #4 during class
- Monday 2/24 - First midterm peer assessment is due
- Monday 4/6 to Friday 4/10 - Advisor team project take-over
- Tuesday 4/14 and Thursday 4/16 - Advisor team presentations during class (take-over memos are due at 1:00pm Tuesday)
- Friday 4/17 - Second midterm peer assessment is due
- Thursday 4/30 - Executive summary is due
- Tuesday 5/5 - Oral presentations during class
- Tuesday 5/8 - Deliverable is due
- Final Exam Slot (date TBD) - Technical report is due
- Friday 5/15 - Final peer assessment is due

### General Schedule

Shown below is a generic schedule illustrating how the course will operate for the majority of the semester:

```{r, echo = FALSE}
tab <- data.frame(Tues = c("Progress Reports (1 + 2)", "Advisor Assessment of progress (3 + 4)", "Time to work/organize"),
                  Thurs = c("Goal Setting (1 + 2)", "Advisor Assessment of goals (3 + 4)", "Time to work/organize"),
                  `Tues ` = c("Progress Reports (3 + 4)", "Advisor Assessment of progress (1 + 2)", "Time to work/organize"),
                  `Thurs ` = c("Goal Setting (3 + 4)", "Advisor Assessment of goals (1 + 2)", "Time to work/organize"))

knitr::kable(tab)

```