---
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

# Syllabus - Sta-230-01 and 02 (Fall 2022)

### Course Information

**Instructor**:

- Ryan Miller, Noyce 2218, millerry\@grinnell.edu

**Class Meetings**: 

- Noyce 2401, 9:00-9:50AM (Sec 01) or 10:00-10:50AM (Sec 02)

**Office Hours**

- Noyce 2218, M 2:00-3:00PM, W 1:00-2:00PM, F 11:00AM-12:00PM, or by appointment

#### Course Description

This course introduces core topics in data science using R programming. This includes introductions to getting and cleaning data, data management, exploratory data analysis, reproducible research, and data visualization. This course incorporates case studies from multiple disciplines and emphasizes the importance of properly communicating statistical ideas. Prerequisite: MAT-209 or STA-209. Suggested CSC-151 or computer programming experience.

#### Texts

There is no required textbook for this course.  All necessary materials will be posted on the [course website](s230f22.html).  At times we will use materials, readings, and exercises from several published textbooks, all of which are freely available online and do not need to be purchased. 

1. [Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/) by Baumer, Kaplan,and Horton
2. [R for Data Science](https://r4ds.had.co.nz/) by Grolemund and Wickham 
3. [An Introduction to Statistical Learning](https://www-bcf.usc.edu/~gareth/ISL/ISLR%20Seventh%20Printing.pdf) by James, Witten, Hastie, and Tibshirani 

<br/><br/>

### Aims and Objectives

This course aims to develop in students an informed critical or theoretical perspective on the social impact of data collection, including the social construction of data production, and the use of algorithmic techniques to process that data.

#### Learning Objectives

After completing this course, students should be able to:

- Translate research questions into quantifiable metrics or models that can be evaluated
- Apply methods of data exploration, visualization, and statistical analysis to illustrate key findings and make justifiable inferences
- Use the `R` programming environment to manage, process, and format unstructured data, to generate meaningful data visualizations, and to fit and evaluate supervised or unsupervised learning models
- Clearly and concisely communicate the results of data-driven analyses to statistical and non-statistical audiences

<br/><br/>

### Policies

**Class Sessions**

The core component of most classes (40-50 minutes) will be working through hands-on labs in a paired programming environment.  For the first few weeks of the semester these groups will be assigned; after that you will be allowed to choose your own partner(s), or work independently.  During labs it is essential that you and your partner(s) work together, making certain that each of you understand your work equally well.

Most labs begin with a short "preamble" section that we will work through together as class. This purpose of this section is to introduce everyone to the topic of the lab and provide an on-ramp into its content.

**Attendance** 

This course involves substantial group work, meaning absences affect not only yourself, but also your classmates.  That said, I understand that missing class is sometimes necessary.  If you will be absent for any reason I ask to be notified as soon as possible. Showing up late or missing class without prior notice will negatively impact the participation component of your grade.

**Software**

Software is an essential component of data science and will a critical component of this course.  We will primarily use `R`, an open-source statistical software program.  The course will involve many guided lab activities in the RStudio environment.  You will also be expected to write, document, and submit code used for projects throughout the semester.

**Academic Honesty**

At Grinnell College you are part of a conversation among scholars, professors, and students, one that helps sustain both the intellectual community here and the larger world of thinkers, researchers, and writers. The tests you take, the research you do, the writing you submit-all these are ways you participate in this conversation.

The College presumes that your work for any course is your own contribution to that scholarly conversation, and it expects you to take responsibility for that contribution. That is, you should strive to present ideas and data fairly and accurately, indicate what is your own work, and acknowledge what you have derived from others. This care permits other members of the community to trace the evolution of ideas and check claims for accuracy.

Failure to live up to this expectation constitutes academic dishonesty. Academic dishonesty is misrepresenting someone else's intellectual effort as your own. Within the context of a course, it also can include misrepresenting your own work as produced for that class when in fact it was produced for some other purpose.  A complete list of dishonest behaviors, as defined by Grinnell College, [can be found here](https://catalog.grinnell.edu/content.php?catoid=12&navoid=2537#alleged-violation).

**Inclusive Classroom**

Grinnell College makes reasonable accommodations for students with documented disabilities.  To receive accommodations, students must provide documentation to the Coordinator for Disability Resources, information [can be found here](http://www.grinnell.edu/about/offices-services/accessibility-disability/disability-services).  If you plan on using accommodations in this course, you should speak with me as early as possible in the semester so that we can discuss ways to ensure your full participation in the course.

**Religious Holidays**

Grinnell College encourages students who plan to observe holy days that coincide with class meetings or assignment due dates to consult with your instructor in the first three weeks of classes so that you may reach a mutual understanding of how you can meet the terms of your religious observance, and the requirements of the course.

<br/><br/>

### Grading

**Engagement and Participation** - 5\%

Participation during a lab-heavy course is absolutely critical. During labs you are expected to help your partner(s) learn the material (which goes beyond simply answering the lab questions).  You will start the semester with a baseline participation score of 80\%, which will then move up or down depending on my subjective assessment of your behavior during class.  You can very quickly raise this score to 100\% by doing a superb job helping your lab partner(s), and working diligently to understand course material during class.  Alternatively, you can lower this score by skipping class, letting your lab partner(s) do most of the work, using your phone or surfing the web during class, etc.  If you are ever unsure of your participation standing, you can email me and I am happy to provide you an interim assessment.

**Labs** - 20\%

Each lab contains embedded questions that you and your lab partner are expected to answer together. Each group member should submit their own copy of the group's answers via P-web prior to the assignments due-date. Some lab questions will be scored for accuracy with feedback given, while others will be scored for effort/completion.  If it becomes clear that you are your partner are using a "divide and conquer" approach to answering lab questions your score on that assignment will be penalized.  Any lab that is turned in after sketch solutions are posted will receive no higher than 60% credit.

**Individual Homework** - 20\%

There will be roughly 5-7 individual homework assignments throughout the semester. These assignments are naturally cumulative, and they are designed to prompt you to use concepts from multiple different labs. You are welcome to get help from DASIL mentors or myself on these assignments, though your submissions should be your own work, and you should add the name(s) of anyone you received help from as a footnote on the question that they helped you with. Most homework will also include a short reading and reflection.

**Midterm Project #1** - 5\%

For this project, you will create 2-3 professional visualizations and post your visualizations with a 100–200-word caption/description for each. You will work on this project in a *group of two of three*. If you combine 2 or more data sources with merging and joining, only 2 visualizations are required. If you use only 1 data source, you are expected to create 3 visualizations. You will be required to peer review 3 other groups, and you can receive a small amount of extra credit for peer reviewing every group. 

You can find details on Midterm #1 [here](s230f22/midterm1.html)

**Midterm Project #2** - 20\%

For this project, you will develop an `R Shiny` app that visually explores a data set of your choosing. You may work on this project individually, or with *one classmate* of your choosing.  You will publish your app online and give a 5 minute in-class presentation demonstrating the capabilities of your app and discussing some of the trends in your data that your app displays. You will be evaluated on both the features of your app and how well you communicate what you see in the data.

You can find details on Midterm #2 [here](s230f22/midterm2.html)

**Final Project** - 30\%

This project is a start-to-finish data science application on a non-trivial data set. The final product is a three-page written report accompanied by R code and documentation. You may work on this project individually, or with *up to two classmates* of your choosing.

You can find details on the final project [here](s230f22/final.html)

$~$

### Misc

**Why use R for Data Science?**

If you’ve spent any amount of time looking into data science online you’ll undoubtedly have noticed the heavy emphasis placed on the Python programming language. Indeed, research from Cal State University found Python was the most popular data science language in private industry, being mentioned in 42% of data scientist job postings. R, which was mentioned in 20% of job postings, is not far behind and offers a few advantages in learning data science skills from a statistical perspective (hence this course having the STA prefix).  

Both R and Python provide plenty of data manipulation functionality. However, because R was created by academic statisticians, it offers very strong data visualization and statistical modeling packages. On the other hand, Python is a general-purpose programming language that excels in production, deployment, and machine learning. Regardless of each language’s strengths and weakness, as an introductory course our focus is on the fundamental skills and thought processes of data science – a goal that can be accomplished regardless of the tools used (which tend to change over time anyways).

**Getting Help**

In addition to visiting office hours, there are many other ways in which you can find help on assignments and projects.

The [Data Science and Social Inquiry Lab (DASIL)](https://www.grinnell.edu/academics/resources/data-inquiry-lab) is staffed by mentors who are experienced in `R` programming and may be able to help troubleshoot problems you are having.  Many students who've previously taken this course have made extensive use of the DASIL work space and its computing resources.

The online platform [Stack Overflow](https://stackoverflow.com/questions/tagged/r) is a useful resource to find user-generated coding solutions to common `R` problems.  Nearly all professional data scientists have needed to "look up" a coding strategy on a site like Stack Overflow at some point in their career, and I have no problem with you doing the same on assignments or projects.  However, if you make substantial use of a Stack Overflow answer (ie: actually integrating lines of code written by someone else into your work, not just getting help identifying the right functions/arguments) the expectation is that you cite or acknowledge doing so.
