---
title: "MATH 156: General Statistics"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
---

## Course Information

**Instructor**:

- Ryan Miller, millerr33\@xavier.edu 

**Class Meetings**: 

- Location: Alter 102, T/TH 8:30-9:45AM (Section 01) and T/TH 10:00-11:15AM (Section 02)

**Office Hours**

- *Virtual* office hours will held at the times listed below in the following Zoom meeting room (see Canvas for the password): https://xavier.zoom.us/my/ryanmiller33
    - Monday 10:00-11:00am
    - Wednesday 2:00-3:00pm
    - Thursday 2:30-3:30pm

## Course Description

An introduction to the major concepts and tools used for collecting, analyzing, and making inferences from data. Topics include: graphical displays, correlation, regression, design of experiments, probability, simulation, random sampling, confidence intervals and hypothesis testing.

### Text

This course will follow the textbook listed below.  Homework problems will be assigned from the text, but readings from the will be optional (though strongly encouraged).

- *Stats, data & models* 5th edition by DeVeaux, Vellemen, and Bock

### Website

- All course materials will be posted on the following webpage: https://remiller1450.github.io/m156f20.html
    - Grades and Quizzes will be posted on Canvas

### Course Aims:

This course intends to teach students to identify patterns in data using visualizations and statistical methods.  It will focus on building foundational understanding of fundamental statistical techniques, proper interpretation of results, and clear communication of these ideas in written and oral formats.

### Learning Objectives:

Specific learning outcomes, with respect to the core curriculum at Xavier, include:

- (1a) Students recognize and cogently discuss significant questions in the humanities, arts, and
the natural and social sciences
- (2a) Students find, evaluate, and logically convey information and ideas in written and oral
form
- (2b) Students evaluate problems using quantitative methods and arguments

### Software

In the modern era, statisticians (along with most scientific professionals) rely upon software to carry out their day to day work. While this course is not intended to be focused on any particular software package, you can expect to use software programs like Microsoft Excel and various online web-applets to explore and analyze real data.

### Course Structure

Due to the ongoing COVID-19 pandemic, students will attend *only one* of the two scheduled in-person class sessions each week.  You will have an opportunity to sign-up to attend day of your choice (either Tuesday or Thursday) prior to the start of the semester.

In a typical week you will be expected to do the following (in this order!):

1. Watch a series of short lecture videos on your own
2. Take an online comprehension quiz covering these videos (can retake twice)
3. Attend your in-person session
4. Upload your write-up from the in-person session to Canvas
5. Complete and electronically submit that week's problem set

Because we may discuss quiz questions as early as Tuesday at 8:30am, *all students* must complete 1 and 2 by 8:30am on Tuesdays.

During in-person class sessions you will practice concepts from these lectures, usually by analyzing interesting real data examples in small groups.

## Grading

**Weekly Assignments**

- Problem Sets - 20%
- In-class Activities - 10%
- Comprehension Quizzes - 10%

There will be 10 roughly problem sets, in-class activities (excluding exams), and comprehension quizzes throughout the semester.  

Problem sets will be assigned from the textbook. They are to be completed individually and submitted via Canvas as a pdf (there are free apps available to help you do this with your cell phone).  Additionally, you *must acknowledge* any sources of collaboration on your submission (ie: write "I worked with Jimmy" on your paper).

Most in-class activities will require you to submit short reflection or summary of the main points of the activity.  This will be done via Canvas, and you will receive credit for the quality of your submissions

Comprehension quizzes are to be completed on Canvas each week.  You may retake these quizzes up to three times to improve your score.

**Exams**

- Exam 1 (Descriptive Statistics and Probability) - 20%
- Exam 2 (Statistical Inference) - 20%

All exams will be announced at least 14 calendar days ahead of time and will be administered via Canvas. Formulas and calculators will be provided as necessary.  You can expect Exam 1 to take place near the mid-point of the semester, and Exam 2 to take place near the end of the semester.

These exams are intended to test how deeply you understand the key concepts of the course, they are not meant to test memorization or arithmetic skills.  Consequently, you should be prepared for a substantial amount of writing during exams.

**Final Project**

- Intermediate Steps - 5%
- Final Report - 15%

Rather than a traditional final exam, this class will feature a comprehensive project.  Additional information will come towards the end of the semester, but you will be given the choice to either a conduct and report on your own analysis of an approved dataset, or summarize and critique the statistical methods used in a published research paper in your primary field of study.  You will have the option to work alone or with a partner of your choosing on this project.

### Overall Course Grades

The following grade cutoffs will be used:

- A [93,100]
- A- [90, 93)
- B+ [87, 90)
- B [83, 87)
- B- [80, 83)
- C+ [77, 80)
- C [73, 77)
- C- [70, 73)
- D+ [67, 70)
- D [63, 67)
- D- [60, 63)
- F [0, 60)

The course instructor reserves the right to adjust these thresholds *downward*, but *not upward* at the end of the semester.  

## Policies

In accordance with the values of Xavier University, students are expected to adhere to the following policies:

### Attendance

Students are expected to attend all scheduled lectures assigned to them.  The instructor reserves the right to lower final course grades in response to repeated, unexcused absences.  Good attendance means more than simply showing up to class, please practice proper etiquette including not being late, refraining from cell-phone use during class, respecting your classmates, and actively participating in class activities to your fullest capacity.

### Attending the Class Virtually

In the event of circumstances that prevent you from physically attending your in-person session, you may attend via Zoom if you communicate your situation in advance and receive instructor approval.  Please note, this class is not intended for a completely remote audience and it will likely be more challenging for you to complete in-class activities virtually.

### Academic Honesty

Students will be required to sign an Honor Pledge on certain assignments: *"As a student at Xavier University, I have neither given nor received unauthorized aid on this assignment/exam. (Student signature)"*.  Assignments and exams will explicitly describe what constitutes authorized versus unauthorized aid.

In general, collaborate work is highly encouraged in this course; however, your homework write-ups should be your own individual work.  Copying solutions from anyone or any source without full disclosure is considered cheating.  If you received help, ideas, or inspiration from anywhere (classmates, online resources, etc.) you should indicate this on your assignment (a simple statement like "I worked with Jack and Jill on problems 1-3" is enough).

### Late Assignments

Late work may be accepted on a case-by-case basis; however, *all* late assignments must be submitted via email.  Quizzes that are taken after the Tuesday 8:30am deadline will be subject to a 0.8 multiplier (ie: a 10/10 becomes and 8/10, and an 8/10 becomes a 6.4/10).  

### Campus Resources

The Math Lab staffs tutors that are specifically intended to provide help in this course.  Please visit the [Math Lab website](https://www.xavier.edu/mathematics-department/math-lab) for hours and additional information.

The Student Support Center has a wide variety of available resources that are not specific to this course but may be beneficial to your overall academic successful.  For more information, visit the [Student Success Center website](https://www.xavier.edu/success/success-coaching/index).

    