---
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

# Sta-230 Syllabus (Fall 2019)

### Course Information

**Instructor**:

- Ryan Miller, Noyce 2217, millerry\@grinnell.edu

**Class Meetings**: 

- Noyce 2402, T/Th 8:30-9:50am

**Office Hours**

- Noyce 2217, M 9:00-10:00AM, W 2:30-3:30PM, Th 10:00-11:00AM, or by appointment

#### Course Description

This course introduces core topics in data science using R programming. This includes introductions to getting and cleaning data, data management, exploratory data analysis, reproducible research, and data visualization. This course incorporates case studies from multiple disciplines and emphasizes the importance of properly communicating statistical ideas. Prerequisite: MAT-209 or STA-209. Suggested CSC-151 or computer programming experience.  

#### Texts

There is no required textbook for this course.  All necessary materials will be posted on the [course website](sta230f19.html).  At times we may incorperate materials, readings, and exercises from several published textbooks, all are freely available online and do not need to be purchased. 

1. [An Introduction to Statistical and Data Science via R](https://moderndive.com/) by Ismay and Kim
2. [R for Data Science](https://r4ds.had.co.nz/) by Grolemund and Wickham 
3. [An Introduction to Statistical Learning](https://www-bcf.usc.edu/~gareth/ISL/ISLR%20Seventh%20Printing.pdf) by James, Witten, Hastie, and Tibshirani 

<br/><br/>

### Aims and Objectives

This course aims to prepare students to answer questions using data-driven approaches.  This includes formulating answerable questions, evaluating the appropriateness of available data for answering these questions, choosing the right data science tools for the job, undertaking the required analyses in a reproducible manner, drawing sound conclusions, and effectively communicating the results to a variety of audiences.

#### Learning Objectives

After completing this course, students should be able to:

- Translate research questions into quantifiable metrics or models that can be evaluated
- Apply methods of data exploration, visualization, and statistical analysis to illustrate key findings and make justifiable inferences
- Use the `R` programming to manage, process, and format unstructured data, to generate meaningful data visualizations, and to fit and evaluate supervised or unsupervised learning models
- Effectively communicate the results of data driven analyses to both statistical and non-statistical audiences

<br/><br/>

### Policies

**Class Sessions**

The core component of most classes (45-60 minutes) will be working through hands-on labs in a paired programming enivornment.  For the first few weeks of the semester these groups will be assigned; after that you will be allowed to choose your own partner(s), or work independently.  During labs it is essential that you and your partner(s) work together, making certain that each of you understands your code equally well.

In addition to labs, most class sessions will begin with a 15-30 minute presentation. These presentations will cover cotent that is important, but might not warrant an entire lab.  Sometimes that content will complement that day's lab, and sometimes it will seem distinct. You will be expected to use the content of these presentations in homework and projects.

**Attendance** 

This course involves substantial group work, meaning absences affect not only yourself, but also your classmates.  That said, I understand that missing class is sometimes necessary.  If you will be absentfor any reason I ask to be notified as soon as possible. Showing up late or missing class without prior notice will negatively impact the participation component of your grade.

**Academic Honesty**

At Grinnell College you join a conversation among scholars, professors, and students, one that helps sustain both the intellectual community here and the larger world of thinkers, researchers, and writers. The tests you take, the research you do, the writing you submit-all these are ways you participate in this conversation.

The College presumes that your work for any course is your own contribution to that scholarly conversation, and it expects you to take responsibility for that contribution. That is, you should strive to present ideas and data fairly and accurately, indicate what is your own work, and acknowledge what you have derived from others. This care permits other members of the community to trace the evolution of ideas and check claims for accuracy.

Failure to live up to this expectation constitutes academic dishonesty. Academic dishonesty is misrepresenting someone else's intellectual effort as your own. Within the context of a course, it also can include misrepresenting your own work as produced for that class when in fact it was produced for some other purpose.  A complete list of dishonest behaviors, as defined by Grinnell College, [can be found here](https://catalog.grinnell.edu/content.php?catoid=12&navoid=2537#alleged-violation).

**Inclusive Classroom**

Grinnell College makes reasonable accommodations for students with documented disabilities.  Students need to provide documentation to the Coordinator for Disability Resources, information [can be found here](http://www.grinnell.edu/about/offices-services/accessibility-disability/disability-services).  Students should then speak with me as early as possible in the semester so that we can discuss ways to ensure your full participation in the course and coordinate your accommodations.

**Religious Holidays**

Grinnell College encourages students who plan to observe holy days that coincide with class meetings or assignment due dates to consult with your instructor in the first three weeks of classes so that you may reach a mutual understanding of how you can meet the terms of your religious observance, and the requirements of the course.

**Getting Help**

The [Data Science and Social Inquiry Lab (DASIL)](https://www.grinnell.edu/academics/resources/data-inquiry-lab) has mentors and tutors who are exprerienced in `R` programming and may be able to help troubleshoot problems you are having.  Many students who've previously taken this course made extensive use of the DASIL workspace and resources.

**Software**

Software is an essential component of data science and will a critical component of this course.  We will primarily use `R`, an open-source statistical software program.  The course will involve many guided lab activities in the RStudio environment.  You will also be expected to write, document, and submit code used for projects throughout the semester.

**Course Outline**

[Click Here to return to the Course Schedule](sta230f19.html)

<br/><br/>

### Grading

**Engagement and Participation** - 10\%

Participation during a lab-heavy course is absolutely critical. During labs you are expected to help your partner(s) learn the material (which goes beyond simply answering the lab questions).  You will start the semester with a participation score of 80\%, which will then move up or down depending on my subjective assessment of your behavior during class.  You can very quickly raise this score to 100\% by doing a superb job helping your lab partner(s), and working dilligently to understand course material during class.  Alternatively, you can lower this score by skipping class, letting your lab partner(s) do most of the work, using your phone or surfing the web during class, etc.  I will provide a midterm update on your participation score, and you may ask me about your approximate standing at any point during the semester.

**Group Labs** - 15\%

Each lab contains embedded questions that you and your lab partner(s) are expected to answer together.  Each group will submit a single set of answers, which are scored primarily for effort.  If it becomes clear that you are your partner are using a "divide and conquer" approach to answering lab questions your score on that assignment will be penalized.

**Individual Homework** - 25\%

Individual homework will be assigned approximately every two weeks (resulting in 5-7 assignments throughout the semester).  You are given two weeks for these assignments because they might take you a while to complete and require a substantial amount of coding in `R`. Coding errors can be difficult to debug, so I advise you to start each assignment as early as possible.  You are welcome to get help from DASIL mentors or myself on these assignments, though your submissions should be your own work, and you should add the name(s) of anyone you received help from as a footnote on the question that they helped you with.

**Midterm Project** - 20\%

For this project you will develop an `R Shiny` app that visually explores a dataset of your choosing. You may work on this project individually, or with *one classmate* of your choosing.  You will publish your app online and give a 5 minute in-class presentation demonstrating the capabilities of your app and discussing some of the trends in your data that the app elucidates. You will be evaluated on both the features of your app and how well you communicate what you see in the data. Additional details can be found in the [Midterm Project Assignment Sheet](s230f19\midterm.html) 

**Final Project** - 30\%

This project is a comprehensive data analysis. You will work with either one or two classmates of your choosing, but you may not work with person you partnered with on the midterm.  The project will include a few short progress reports before culminating in a short in-class presentation and a 3 page written report in the last week of the semester. Additional details can be found in the [Final Project Assignment Sheet](s230f19\final.html) 