---
title: "MATH 257: Data Modeling"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
---

## Course Information

**Instructor**:

- Ryan Miller, millerr33\@xavier.edu 

**Class Meetings**: 

- Location: Alter 101, T/TH 1-2:15pm

**Office Hours**

- *Virtual* office hours will held at the times listed below in the following Zoom meeting room (see Canvas for the password): https://xavier.zoom.us/my/ryanmiller33
    - Monday 10:00-11:00am
    - Wednesday 2:00-3:00pm
    - Thursday 2:30-3:30pm

## Course Description

Exploratory data analysis and visualization, logistic regression, estimation and inference of multiple regression models, model selection, analysis of variance, multiple comparisons, and experimental design.

### Textbooks

Readings and homework questions will be assigned from the sources listed below.

1. [A Second Course in Statistics: Regression Analysis](https://www.pearson.com/store/p/second-course-in-statistics-a-regression-analysis/P100000772506/9780321831453?tab=table-of-contents) 7th edition (2012) by Mendenhall and Sincich 
2. [An Introduction to Statistical Learning](https://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf) by James, Witten, Hastie, and Tibshirani (free and online)
3. [R for Data Science](https://r4ds.had.co.nz/) by Grolemund and Wickham (free and online) 

### Website

- Some materials can be found the course Canvas page; however, most will be links to: https://remiller1450.github.io/m257s21.html, where you will find everything for the course (other than your grades)

### Course Aims:

This primary aim of this course is to provide students with hands on experience implementing statistical models to real datasets in the `R` programming environment.  This includes all steps of the analysis pipeline, including: exploratory data analysis and data visualization, model selection, model evaluation, and statistical inference 

### Learning Objectives:

Specific learning outcomes, with respect to the curriculum guidelines at Xavier, include:

- (1a) Students recognize and cogently discuss significant questions in the humanities, arts, and
the natural and social sciences
- (2a) Students find, evaluate, and logically convey information and ideas in written and oral
form
- (2b) Students evaluate problems using quantitative methods and arguments

### Software

In the modern era, statisticians (along with most scientific professionals) rely upon software. In this course you will be required to use `R` (typically through the `R Studio` GUI).  `R` is an open-source software that is generally regarded as the industry standard amongst professional statisticians.  Throughout the course you will work through guided labs which will simultaneously promote proficiency in `R` programming and applied statistical analysis.

You can install `R` and `R Studio` on your personal computer in two easy steps:

1.	First, download and install `R` from http://www.r-project.org/
2.	Second, download and install the `R Studio` user interface from http://www.rstudio.com/ 

R Studio is also installed and available on some campus computers.

### Course Structure

We are fortunate to have a large enough classroom and a small enough class size to enable the course to operate as it normally would in past years.  For this reason, all students are expected to attend class in-person on both Tuesday and Thursday.  Accordingly, attendance via Zoom is only acceptable if you have a verified medical reason for not attending class in-person.

Because data modeling is such a hands-on subject, the majority of class time will be devoted to working through guided labs in a paired programming setting.  In a typical week you might expect the following:

- Tuesday:
    - Short 20-30 minute lecture introducing a topic
    - 40-45 minutes to start that week's lab
- Thursday:
    - Another 20-30 minute lecture expanding upon Tuesday's topic or presenting a case study
    - 40-45 minutes to finish that week's lab

You are expected to use our in-class time wisely and as an instructor I will be checking in with each pair/individual regularly throughout the time devoted to lab.

## Policies

In accordance with the values of Xavier University, students are expected to adhere to the following policies:

### Attendance

Students are expected to attend all scheduled class sessions. The instructor reserves the right to lower final course grades in response to repeated, unexcused absences.  Good attendance means more than simply showing up to class, please practice proper etiquette including not being late, refraining from cell-phone use during class, respecting your classmates, and actively participating in class activities to your fullest capacity.

### Academic Honesty

Students will be required to sign an Honor Pledge on certain assignments: *"As a student at Xavier University, I have neither given nor received unauthorized aid on this assignment/exam. (Student signature)"*.  Assignments and exams will explicitly describe what constitutes authorized versus unauthorized aid.

In general, collaborate work is highly encouraged in this course; however, your homework write-ups should be your own individual work.  Copying solutions from anyone or any source without full disclosure is considered cheating.  If you received help, ideas, or inspiration from anywhere (classmates, online resources, etc.) you should indicate this on your assignment (a simple statement like "I worked with Jack and Jill on problems 1-3" is enough).

### Campus Resources

MATH 257 is a major-level course, so drop-in tutoring at the Mathematics Lab and one-on-one tutoring through the Office of Academic Support are generally not available.  The first place you should go with questions related to course material is the course instructor.  Additionally, the Student Support Center has a wide variety of available resources that are not specific to this course but may be beneficial to your overall academic successful.  For more information, visit the [Student Success Center website](https://www.xavier.edu/success/success-coaching/index).


## Grading

**Projects**

- Midterm #1 (Data Exploration and Basic Models) - 15%
- Midterm #2 (Multi-variable Models) - 15%
- Final (Comprehensive) - 25%

**Problem Sets**

- 5ish problem sets - 15%

These are intended to be on-your-own practice with key course concepts. Questions will be assigned out of the course textbooks. You will have 2-3 weeks to work indpendently on each problem set, with due-dates typically being on Fridays.

**In-class Labs**

- 10ish weekly in-class labs - 25%

These are intended to be completed primary (90%+) during classtime with a partner.  Often we will go over some of the lab questions together while we are working on the lab, with the remaining questions being used to determine your score.

**Attendance and Participation**

- Satisfactory attendence and participation during class - 5%

As an incentive to dilligently attend class and participate, the remaining 5% of your end-of-semester grade will be determined by your attendence and participation record. While this grade is inherently subjective, as long as you are regularly coming to class, communicating any absences ahead of time, and using class-time appropriately you can expect to receive a full-credit in this category.


### Overall Course Grades

The following grade cutoffs will be used:

- A [93,100]
- A- [90, 93)
- B+ [87, 90)
- B [83, 87)
- B- [80, 83)
- C+ [77, 80)
- C [73, 77)
- C- [70, 73)
- D+ [67, 70)
- D [63, 67)
- D- [60, 63)
- F [0, 60)

The course instructor reserves the right to adjust these thresholds *downward*, but *not upward* at the end of the semester.  
