---
title: "Sta-209 Schedule (Fall 2019)"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

You can scroll down this page, or use the navigation panel on the left side of this page to view the course schedule.

You can [click here](https://remiller1450.github.io/sta209f19.html) to return to the course homepage.

<br/><br/>

## August and September

### Week 1 (8/30)

**In Class**:

- Friday 8/30
    - Discuss the [syllabus](syllabus209f19.html)
    - [Introduction to Statistics](s209f19/intro_h.pdf)

**Suggested Readings**:

- Ch 1.1 (Friday)
    
**Assignments**:

- First Day Survey (due Monday 9/2)

**Assignments Due**:

- None

<br/><br/>
<br/><br/>

### Week 2 (9/2 - 9/6)

**In Class**:

- Monday 9/2
    - [Summarizing Data](s209f19/sum_h.pdf)
    - Start [Lab #1 - Descriptive Statistics and Graphs](s209f19/Lab1.html)

- Wednesday 9/4
    - Finish Lab #1

- Friday 9/6
    - Discuss Lab #1
    - Populations and Samples

**Suggested Readings**:

- Ch 2.1-2.2 (Monday)
- Ch 2.3-2.5 (Wednesday)
- Ch 1.2 (Friday)
    
**Assignments**:

- Lab #1 (due Friday 9/6)
- Homework #1 - 1.15, 1.16, 1.22, 2.20, 2.66, 2.116 2.117, 2.118 (due Friday 9/6)

**Assignments Due**:

- First Day Survey (due Monday 9/2)
- Lab #1 (due Friday 9/6)
- Homework #1 - 1.15, 1.16, 1.22, 2.20, 2.66, 2.116 2.117, 2.118 (due Friday 9/6)

<br/><br/>
<br/><br/>

### Week 3 (9/9 - 9/13)

**In Class**:

- Monday 9/9
    - Lab #2 - Confounding Variables

- Wednesday 9/11
    - Discuss Lab #2
    - Randomized Experiments

- Friday 9/13
    - Sampling Distributions

**Suggested Readings**:

- Ch 1.3 (Monday)
- Ch 3.1 (Friday)
    
**Assignments**:

- Lab #2 (due Wednesday 9/11)
- Homework #2 - 1.40, 1.41, 1.42, 1.43, 1.44, 1.45, 1.60, 1.91, 1.92, 1.100, 1.103 (due Friday 9/13)

**Assignments Due**:

- Lab #2 (due Wednesday 9/11)
- Homework #2 - 1.40, 1.41, 1.42, 1.43, 1.44, 1.45, 1.60, 1.91, 1.92, 1.100, 1.103 (due Friday 9/13)

<br/><br/>
<br/><br/>

### Week 4 (9/16 - 9/20)

**In Class**:

- Monday 9/16
    - Confidence Intervals
    - Start Lab #3 - Bootstrapping
    
- Wednesday 9/18
    - Finish Lab #3

- Friday 9/20
    - Normal Approximations (part 1)

**Suggested Readings**:

- Ch 3.2-3.3 (Monday)
- Ch 3.3-3.4 (Wednesday)
- Ch 5.1 (only pages 372-275) and Ch 5.2 (Friday)
    
**Assignments**:

- Lab #3 (due Friday 9/19)
- Homework #3 - 3.25, 3.26, 3.29, 3.58, 3.64 3.93, 3.94, 3.102, 3.125, 3.130 (due Friday 9/19)

**Assignments Due**:

- Lab #3 (due Friday 9/19)
- Homework #3 - 3.25, 3.26, 3.29, 3.58, 3.64 3.93, 3.94, 3.102, 3.125, 3.130 (due Friday 9/19)

<br/><br/>
<br/><br/>

### Week 5 (9/23 - 9/27)

**In Class**:

- Monday 9/23
    - Normal Approximations (part 1/part 2)
    
- Wednesday 9/25
    - Normal Approximations (part 2)
    
- Friday 9/27
    - Lab #4 - Confidence Intervals
        
**Suggested Readings**:

- Ch 6.1-CI and Ch 6.3-CI (Monday) 
- Ch 6.2-CI and Ch 6.4-CI (Wednesday)  
    
**Assignments**:

- Lab #4 (due Monday 9/30)
- Homework #4 - 5.43, 5.52, 6.20, 6.26, 6.30, 6.143, 6.144, 6.96, 6.97, 6.98 (due Friday 9/27)

**Assignments Due**:

- Homework #4 - 5.43, 5.52, 6.20, 6.26, 6.30, 6.143, 6.144, 6.96, 6.97, 6.98 (due Friday 9/27)

<br/><br/>
<br/><br/>

## October

### Week 6 (9/30 - 10/4)

**In Class**:

- Monday 9/30
    - Null Distributions and p-values

- Wednesday 10/2
    - Review for Exam #1

- Friday 10/4
    - Exam #1

**Suggested Readings**:

- Ch 4.1 and 4.2 (Monday) 
    
**Assignments**:

- HW #5 - 6.143, 6.148, 6.195, 6.196, 6.206 (due *Wednesday* 10/2)

**Assignments Due**:

- Lab #4 (due Monday 9/30)
- HW #5 - 6.143, 6.148, 6.195, 6.196, 6.206 (due *Wednesday* 10/2)

<br/><br/>
<br/><br/>

### Week 7 (10/7 - 10/11)

**In Class**:

- Monday 10/7
    - Finish Null Distributions and p-values
    - Randomization Tests 

- Wednesday 10/9
    - Lab #5 - Randomization Testing 

- Friday 10/11
    - Testing Errors, Power, and Multiple Comparisons

**Suggested Readings**:

- Ch 4.3 (Monday) 
- Ch 4.4 and 4.5 (Friday)
    
**Assignments**:

- HW #6 - 4.16, 4.18, 4.65, 4.66, 4.68, 4.101, 4.102, 4.113, 4.114 (due Friday 10/11)

**Assignments Due**:

- HW #6 - 4.16, 4.18, 4.65, 4.66, 4.68, 4.101, 4.102, 4.113, 4.114 (due Friday 10/11)
- Lab #5 (due at midnight on Friday 10/11)

<br/><br/>
<br/><br/>

### Week 8 (10/14 - 10/18)

**In Class**:

- Monday 10/14
    - Finish Testing Errors, Power, and Multiple Comparisons
    - Start Normal Approximations for Hypothesis Testing

- Wednesday 10/16
    - Normal Approximations for Hypothesis Testing
    
- Friday 10/18
    - Lab #6 - A/B Testing

**Suggested Readings**:

- Ch 5.1 (Monday) 
- Ch 6.1-HT and 6.3-HT (Wednesday) 
    
**Assignments**:

- HW #7 - 4.144, 4.145, 6.56, 6.57, 6.60, 6.163, 6.164, 1.165 (due Friday 10/18)
- Lab #6 (due Monday 10/28)

**Assignments Due**:

- HW #7 - 4.144, 4.145, 6.56, 6.57, 6.60, 6.163, 6.164, 6.165 (due Friday 10/18)

<br/><br/>
<br/><br/>

**FALL BREAK (10/21 - 10/24)**

<br/><br/>
<br/><br/>

### Week 9 (10/28 - 11/1)

**In Class**:

- Monday 10/28
    - Hypothesis Testing with the $t$-distribution

- Wednesday 10/30
    - Transformations and Outliers

- Friday 11/1
    - Lab #7 - Hypothesis Testing

**Suggested Readings**:

- Ch 6.2-HT, 6.4-HT, 6.5 (Monday/Wednesday) 
    
**Assignments**:

- HW #8 - 6.121, 6.122, 6.215, 6.216, 6.250, 2.256, [additional questions #1 and #2](s209f19/f19s209hw8.html)
- Lab #7 - Due Monday 11/14

**Assignments Due**:

- Lab #6 (due Monday 10/28)
- HW #8 (due Friday 11/1)

<br/><br/>
<br/><br/>

## November

### Week 10 (11/4 - 11/8)

**In Class**:

- Monday 11/4
    - Chi-Squared Testing

- Wednesday 11/6
    - Chi-Squared Testing (continued)
    
- Friday 11/8
    - Review for Exam 2

**Suggested Readings**:

- Ch 7.1 and 7.2 (Monday and Wednesday)
    
**Assignments**:

- HW #9: 7.13, 7.20, 7.26, 7.27, 7.43, 7.44, 7.46 (due Friday 11/8)

**Assignments Due**:

- Lab #7 (due Monday 11/4)

<br/><br/>
<br/><br/>

### Week 11 (11/11 - 11/15)

**In Class**:

- Monday 11/11
    - Lab #8 - Chi-Squared Tests and More (due Wednesday 11/13)

- Wednesday 11/13
    - Practice exam during class

- Friday 11/15
    - Exam #2
    
**Assignments**:

- Lab #8 (due Wednesday 11/13)

**Assignments Due**:

- Lab #8 (due Wednesday 11/13)

<br/><br/>
<br/><br/>

### Week 12 (11/18 - 11/22)

**In Class**:

- Monday 11/18
    - Finish study design notes
    - Start ANOVA

- Wednesday 11/20
    - ANOVA

- Friday 11/22
    - Lab #9 (due Wednesday 11/27)

**Suggested Readings**:

- Ch 8.1 and 8.2 (Monday and Wednesday)
    
**Assignments**:

- HW #10: 8.8, 8.15, 8.16, 8.17, 8.18, 8.32 (due Friday)

**Assignments Due**:

- HW #10

<br/><br/>
<br/><br/>


### Week 13 (11/25 - 11/27)

**In Class**:

- Monday 11/25
    - Regression (part I)

- Wednesday 11/27
    - Regression (part II)

- Friday 11/29 (no class)
    - Happy Thanksgiving!

**Suggested Readings**:

- Ch 2.6 (Monday)
- 
    
**Assignments**:

**Assignments Due**:

<br/><br/>
<br/><br/>

## December

### Week 14 (12/2 - 12/6)

**In Class**:

- Monday 12/2
    - Regression (part III)
    
- Wednesday 12/4
    - Group meetings

- Friday 12/6
    - Lab #10
    
**Assignments**:

**Assignments Due**:

<br/><br/>
<br/><br/>

### Week 15 (12/9 - 12/13)

**In Class**:

- Monday 12/9
    - Lab #10

- Wednesday 12/11
    - Final project presentations 

- Friday 12/13
    - Final project presentations 
    
**Assignments**:

**Assignments Due**:

<br/><br/>
<br/><br/>

### Exam Week (12/16 - 12/20)

**Information Coming Soon**
