---
title: "Sta-230 Schedule (Fall 2019)"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

You can scroll down this page, or use the navigation panel on the left side of this page to view the course schedule.

<br/><br/>

## August and September

### Week 1 (8/29 - 8/30)

**In Class**:

- Thursday 8/29
    - Discuss the [syllabus](syllabus230f19.html)
    - [NYPD Activity](s230f19/Using_Data.html)
    
**Assignments**:

- First Day Survey (due Monday 9/2)

**Assignments Due**:

- None


<br/><br/>
<br/><br/>

### Week 2 (9/2 - 9/6)

**In Class**:

- Tuesday 9/3
    - Summary Statistics Presentation
    - Intro to R Lab


- Thursday 9/5
    - The Simple-to-Complex Principle Presentation
    - Tidy Data Lab

**Suggested Readings**:

- [Modern Dive Ch 1 "Getting Started with Data in R"](https://moderndive.com/1-getting-started.html) (Tuesday)
- [R FAQ and Common Errors](s230f19/R_FAQ_Errors.html) (Tuesday)
- [R for Data Science Ch 12 "Tidy data"](https://r4ds.had.co.nz/tidy-data.html) (Thursday)
    
**Assignments**:

- Lab Questions Set #1 (due Tuesday 9/10)
- Individual Problem Set #1 (due Friday 9/13)

**Assignments Due**:

- First Day Survey (due Monday 9/2)

<br/><br/>
<br/><br/>

### Week 3 (9/9 - 9/13)

**In Class**:

- Tuesday 9/10
    - Variable Transformations Presentation
    - Data Wrangling Lab

- Thursday 9/12
    - Smoothing Presentation
    - Data Visualization (ggplot2) Lab 

**Suggested Readings**

- [R for Data Science Ch 4 "Data Transformation"](https://r4ds.had.co.nz/transform.html) (Tuesday)
- [Simplify your code with %>%](https://uc-r.github.io/pipe) (Tuesday)
- [Modern Dive Ch 3 "Data Wrangling"](https://moderndive.com/3-wrangling.html) (Tuesday)
- [R for Data Science Ch 3 "Data Visualization"](https://r4ds.had.co.nz/data-visualisation.html) (Thursday)
- [Modern Dive Ch 2 "Data Visualization"](https://moderndive.com/2-viz.html) (Thursday)
    
**Assignments**:

- Lab Questions Set #2 (due Tuesday 9/17)

**Assignments Due**:

- Lab Questions Set #1 (due Tuesday 9/10)
- Individual Problem Set #1 (due Friday 9/13)

<br/><br/>
<br/><br/>

### Week 4 (9/16 - 9/20)

**In Class**:

- Tuesday 9/17
    - Density Estimation Presentation
    - Interactive Visualization (plotly) Lab

- Thursday 9/19
    - Visualization Principles Presentation
    - Merging and Joining Lab

**Suggested Readings**:

- [Data Visualization: basic principles by Peter Aldhous (UC-Berkeley, BuzzFeed News)](https://paldhous.github.io/ucb/2016/dataviz/week2.html) (Tuesday)
- [Interactive web-based data visualization with R, plotly, and shiny - Chapters 2 and 3 "Overview" and "Scattered Foundations"](https://plotly-r.com/index.html) (Tuesday)
- [R for Data Science Ch 13 "Relational Data"](https://r4ds.had.co.nz/relational-data.html) (Thursday)
    
**Assignments**:

- Lab Questions Set #3 (due Tuesday 9/24)
- Individual Problem Set #2 (due Friday 9/27)

**Assignments Due**:

- Lab Questions Set #2 (due Tuesday 9/17)

<br/><br/>
<br/><br/>

### Week 5 (9/23 - 9/27)

**In Class**:

- Tuesday 9/24
    - Making Maps Lab

- Thursday 9/26
    - Intro to Text Analysis Presentation
    - String Processing Labs

**Suggested Readings**

- [R Studio's `leaflet` tutorial](https://rstudio.github.io/leaflet/) (Tuesday)
- [R for Data Science Ch 14 "Strings"](https://r4ds.had.co.nz/strings.html) (Thursday)
- [`stringr` package vignette](https://cran.r-project.org/web/packages/stringr/vignettes/stringr.html) (Thursday)    
    
**Assignments**:

- Lab Questions Set #4 (due Tuesday 10/1)

**Assignments Due**:

- Lab Questions Set #3 (due Tuesday 9/24)
- Individual Problem Set #2 (due Friday 9/27)

<br/><br/>
<br/><br/>

## October

### Week 6 (9/30 - 10/4)

**In Class**:

- Tuesday 10/1
    - R Shiny Presentation
    - Time to work on Midterm Project
    
- Thursday 10/3 
    - Group Project Meetings (during/outside of class)
    
**Assignments**:

- Work on your project

**Assignments Due**:

- Lab Questions Set #4 (due Tuesday 10/1)

<br/><br/>
<br/><br/>

### Week 7 (10/7 - 10/11)

**In Class**:

- Tuesday 10/8
    - Principal Component Analysis Presentation
    - Principal Component Analaysis Lab
    
- Thursday 10/10
    - Principal Component Analysis Case Study
    - Principal Component Analaysis Lab (continued)
    
**Assignments**:

- Individual Problem Set #3 (due *Monday* 10/28)
- Lab Questions Set #4 (due *Monday* 10/21)

**Assignments Due**:

- Nothing is due this week

<br/><br/>
<br/><br/>

### Week 8 (10/14 - 10/18)

**In Class**:

- Tuesday 10/15
    - Midterm Presentations

- Thursday 10/17
    - Midterm Presentations
    
**Assignments**:

- No new assignments this week

**Assignments Due**:

- Midterm Project Code and Published App (due Friday 10/18)
- Lab Questions Set #4 (due *Monday* 10/21)

<br/><br/>
<br/><br/>

**FALL BREAK (10/21 - 10/24)**

<br/><br/>
<br/><br/>

### Week 9 (10/28 - 11/1)

**In Class**:

- Tuesday 10/29

- Thursday 10/31

    
**Assignments**:

**Assignments Due**:

- Individual Problem Set #3 (due *Monday* 10/28)

<br/><br/>
<br/><br/>

## November

### Week 10 (11/4 - 11/8)

**In Class**:

- Tuesday 11/5

- Thursday 11/7

    
**Assignments**:

**Assignments Due**:

<br/><br/>
<br/><br/>

### Week 11 (11/11 - 11/15)

**In Class**:

- Tuesday 11/12

- Thursday 11/14

**Assignments**:

**Assignments Due**:

<br/><br/>
<br/><br/>

### Week 12 (11/18 - 11/22)

**In Class**:

- Tuesday 11/19

- Thursday 11/21

**Assignments**:

**Assignments Due**:

<br/><br/>
<br/><br/>

### Week 13 (11/25 - 11/29)

**In Class**:

- Tuesday 11/26

- Thursday 11/28 (no class)
    - Happy Thanksgiving!
    
**Assignments**:

**Assignments Due**:

<br/><br/>
<br/><br/>

## December

### Week 14 (12/2 - 12/6)

**In Class**:

- Tuesday 12/3
    
- Tuesday 12/5

    
**Assignments**:

**Assignments Due**:

<br/><br/>
<br/><br/>

### Week 15 (12/9 - 12/13)

**In Class**:

- Tuesday 12/10 (no class)
    - Final project meetings
    
- Tuesday 12/15 (no class)
    - Final project meetings
    
**Assignments**:

**Assignments Due**:

<br/><br/>
<br/><br/>

### Exam Week (12/16 - 12/20)

- Date TBD
    - Final project presentations
    
- Friday 12/20
    - Final paper and code due (emailed before 5:00pm)
