---
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

# Sta-209 Syllabus (Spring 2020)

### Course Information

**Instructor**:

- Ryan Miller, Noyce 2217, millerry\@grinnell.edu

**Class Meetings**: 

- Noyce 2401, M/W/F 1:00-2:20PM

**Office Hours**

- Noyce 2217, M 2:30-3:30PM, T 2:30-3:30PM, Th 3:30-4:30PM, or by appointment

#### Course Description

This course covers the application of basic statistical methods such as univariate graphics and summary statistics, basic statistical inference for one and two samples, linear regression (simple and multiple), one- and two-way ANOVA, and categorical data analysis.  Students use statistical software to analyze data and conduct simulations.  

#### Text

- [Statistics: Unlocking the Power of Data, 2nd Edition](https://www.wiley.com/en-us/Statistics%3A+Unlocking+the+Power+of+Data%2C+2nd+Edition-p-9781119308843) by Robin H. Lock, Patti Frazer Lock, Kari Lock Morgan, Eric F. Lock, Dennis F. Lock (required)

Please note:

- You'll need the second edition or the homework problems won't match-up
- A copy of the text is available for short-term use in Kistle Science Library

<br/><br/>

### Aims and Objectives

This course aims to introduce students to the field of statistics, including its vocabulary and fundamental principles.  The course will prepare to students to read, recognize, interpret, and discuss statistical concepts and their use in scientific applications.  The course will provide students an understanding of the role of statistics within in the scientific method, and provide students the tools to use data to make informed conclusions.

#### Learning Objectives

After completing this course, students should be able to:

- Apply methods of exploration, visualization, and statistical analysis to data in order to illustrate key findings and make justifiable inferences using statistical software (Minitab)
- Communicate the methods and results of statistical analyses succinctly and accurately in both writing and speaking
- Read, identify, and critique the statistical concepts and choices of data presentation used in various media publications (newspaper articles, reports, blogs, etc.)

<br/><br/>

### Policies

**Attendance**

No formal attendance will be kept; however, seats will be randomly assigned for almost every class meeting, making it obvious when you are not in class.  Additionally, as an instructor, I cannot assess your engagement with course material if you are not in class, so a large number of absences (especially if they are unexcused) will negatively affect the "Engagement and Participation" component of your grade.  That said, I understand that there are numerous valid reasons for missing class; and I also understand that unexpected events can lead to absences during the semester.  If you will be missing class for any reason I ask to be notified as soon as possible.

**Academic Honesty**

At Grinnell College you join a conversation among scholars, professors, and students, one that helps sustain both the intellectual community here and the larger world of thinkers, researchers, and writers. The tests you take, the research you do, the writing you submit-all these are ways you participate in this conversation.

The College presumes that your work for any course is your own contribution to that scholarly conversation, and it expects you to take responsibility for that contribution. That is, you should strive to present ideas and data fairly and accurately, indicate what is your own work, and acknowledge what you have derived from others. This care permits other members of the community to trace the evolution of ideas and check claims for accuracy.

Failure to live up to this expectation constitutes academic dishonesty. Academic dishonesty is misrepresenting someone else's intellectual effort as your own. Within the context of a course, it also can include misrepresenting your own work as produced for that class when in fact it was produced for some other purpose.  A complete list of dishonest behaviors, as defined by Grinnell College, [can be found here](https://catalog.grinnell.edu/content.php?catoid=12&navoid=2537#alleged-violation).

**Inclusive Classroom**

Grinnell College makes reasonable accommodations for students with documented disabilities. Students need to provide documentation to the Coordinator for Student Disability Resources, John Hirschman, located on the 3rd floor of Goodnow Hall (x3089) and discuss your needs. Students should then notify me within the first few days of classes so that we can discuss ways to ensure your full participation in the course and coordinate your accommodations.  Additional information [can be found here](http://www.grinnell.edu/about/offices-services/accessibility-disability/disability-services).

**Religious Holidays**

Grinnell College encourages students who plan to observe holy days that coincide with class meetings or assignment due dates to consult with your instructor in the first three weeks of classes so that you may reach a mutual understanding of how you can meet the terms of your religious observance, and the requirements of the course.

**Getting Help**

The Math Lab (Mathematics Learning Center - 2012 Noyce Science Center) has tutors in statistics that are available 7 days a week.  See the website for additional information and hours: http://www.grinnell.edu/academics/areas/math-stats/math-lab 

The Writing Lab, located in HSSC N3129, supports students working on papers, projects, and presentations.  For a link to the schedule and appointment system, search "Writing Lab" on grinnell.edu or grinnellshare.grinnell.edu.

**Software**

This course will make use of Minitab for in class labs and out of class assignments.  Minitab is available on many campus computers and on our classroom computers.  In recent years computing has become an essential part of statistics.  While our course materials will be based on Minitab, other programs are more frequently used by statisticians and I encourage interested students to explore other tools throughout the course, particularly on the final project.

**Course Website**

[Click Here](sta209s20.html) to visit the course webpage containing course materials.

<br/><br/>

### Grading

**Engagement, Participation, and Labs** - 15\%

Active participation during class is expected. Everyone will start with a participation score of 80\%, which will move up or down depending upon my subjective assessment of your engagement during class. If you attend class and you are on-task most of the time this score will increase to 90\%. If I observe you consistently helping your classmates better understand the material, answering questions during lecture, and leading your group during labs this score will increase above 90\%.  If you are consistently off-task (on your phone, surfing the web, sleeping, engaging others in off-topic chatter, skipping class without notice, etc.) this score will decrease, especially if your behavior interferes with the ability of classmates to learn.

Roughly 1/3 of class-time will be spend working on in-class labs in small groups.  After each lab your group will submit a single lab write-up, these write-ups are graded (albeit more leniently than other assignments).  Participation during labs is crucial; more important than answering the lab questions is helping your group members understand the material.  If I discover that your group used a "divide-and-conquer" strategy to answer the lab's questions your score on the lab will be penalized.  Additionally, a *confidential* group [feedback form](https://forms.gle/wNWRFMbbra8oK4LJ8) will remain open throughout the semester. You may use this form to report on group members who are not making an appropriate effort, or you may use it to report on group members who went above and beyond to help you.  If feedback provided through this form aligns with my own observations it will impact lab and/or participation scores.

Labs will done primarily during class and there is no rush to complete them, I am usually happy to devote more class-time to a lab if most groups are still working on it, so rushing through a lab by divvying up the questions hurts not only the members of your group but also the class as a whole.

**Homework** - 15\%

Homework will be assigned once per week.  No late homework will be accepted (unless my permission is obtained *in advance* of the due date), but your lowest two (2) scores will be dropped.  Homework is due at the beginning of class on the specified due date.  Please turn in a paper copy of your assignment, including any printed graphs (if they are asked for). 

I encourage you to work with other students or visit the Math Lab for help on homework questions, but you should clearly understand all your answers and your assignment should be entirely in your own words.  If you engage in significant collaboration with classmates or tutors, you must explicitly acknowledge that person(s) on the top of your assignment (again, you are encouraged to collaborate, I want to emphasize that there is no penalty for doing so).

**Exams (3)** - 15\%, 15\%, 20\%

Exam dates will be announced at least two weeks in advance. Exams will be closed notes (I will provide a formula sheet) and only basic scientific calculators will be allowed (ie: no cellphones or TI-8X graphing calculators).  You are expected to take the exam on the scheduled date and time, if you have a conflict with an exam date make sure to notify me immediately.  Alternative exam arrangements need to be made at least one week in advance of the time you plan to take the exam; this includes taking the exam in a different location, or times going beyond the given class time.  Alternative arrangements are not guaranteed unless proper notification is given.

**Final Project** - 20\%

There will be an ongoing group project throughout the semester. The project will include a few short progress reports before culminating in a short in-class presentation and a three (3) page written report in the last week of the semester. Details can be found in the [Final Project Assignment Sheet](s209s20\project209.html) 